window.LESSON_DATA_20260723 = {

  lesson: {
    id: "2026-07-23",
    date: "2026-07-23",
    title: "AULA 15: Sábado à Tarde com os Amigos — Churrasco e Conversa Natural",
    theme: "チュラスコ・自然な会話・挨拶",
  },

  cards: [

    // ---- 語彙（チュラスコ・状況）---------------------------------

    {
      id: "2026-07-23-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "churrasco",
      back: "ブラジル風バーベキュー（= Brazilian BBQ）",
      example_pt: "Fomos convidados para um churrasco na casa deles.",
      example_ja: "彼らの家のバーベキューに招待された。",
      notes: "ブラジル文化の中心。週末の集まりのほぼ定番。churrasqueiro = BBQを担当する人",
    },
    {
      id: "2026-07-23-vocab-002",
      category: "vocabulary",
      subcategory: "word",
      front: "churrasqueira",
      back: "バーベキューグリル（= BBQ grill）",
      example_pt: "A carne ainda está na churrasqueira.",
      example_ja: "肉はまだグリルの上にある。",
      notes: "churrasqueira = グリル本体。churrasco = バーベキューイベント全体",
    },
    {
      id: "2026-07-23-vocab-003",
      category: "vocabulary",
      subcategory: "word",
      front: "estacionamento",
      back: "駐車場（= parking lot）",
      example_pt: "Eu gastei muito tempo procurando um lugar pra estacionar.",
      example_ja: "駐車場を探すのにすごく時間がかかった。",
      notes: "estacionar（動詞）= 駐車する。estacionamento（名詞）= 駐車場",
    },
    {
      id: "2026-07-23-vocab-004",
      category: "vocabulary",
      subcategory: "word",
      front: "trânsito",
      back: "交通、渋滞（= traffic）",
      example_pt: "O trânsito estava horrível hoje.",
      example_ja: "今日は渋滞がひどかった。",
      notes: "estar no trânsito = 渋滞にはまっている。trânsito intenso = 激しい交通",
    },
    {
      id: "2026-07-23-vocab-005",
      category: "vocabulary",
      subcategory: "word",
      front: "atrasado",
      back: "遅刻した（= late）",
      example_pt: "Eu cheguei atrasado, me desculpa.",
      example_ja: "遅くなってすみません。",
      notes: "chegar atrasado = 遅れて到着する。me desculpa = ごめんなさい（カジュアル）",
    },
    {
      id: "2026-07-23-vocab-006",
      category: "vocabulary",
      subcategory: "expression",
      front: "cerca de",
      back: "〜くらい、約〜（= about / approximately）",
      example_pt: "Há cerca de dez pessoas.",
      example_ja: "10人くらいいる。",
      notes: "mais ou menos と同じ意味。少しフォーマルな印象。Há = há（haver） = there are",
    },
    {
      id: "2026-07-23-vocab-007",
      category: "vocabulary",
      subcategory: "expression",
      front: "por volta das",
      back: "〜頃（時間）（= around / at about）",
      example_pt: "Chegamos por volta das 16h.",
      example_ja: "16時頃に着いた。",
      notes: "時刻と一緒に使う。por volta das 8h = 8時頃。da / das = 時間によって変わる",
    },
    {
      id: "2026-07-23-vocab-008",
      category: "vocabulary",
      subcategory: "word",
      front: "catimba / catimbento",
      back: "反則ギリギリの行為・ずるいプレー（= diving / dirty play）",
      example_pt: "A Argentina é muito catimbenta. A Argentina faz muita catimba.",
      example_ja: "アルゼンチンはずるいプレーが多い。",
      notes: "catimba = 汚いプレー全般。catimbento = そういうプレーをする選手・チーム",
    },

    // ---- 挨拶・チュラスコ到着時の表現 ---------------------------

    {
      id: "2026-07-23-phrase-001",
      category: "phrase",
      subcategory: "greeting",
      front: "E aí, tudo bem? / E aí, beleza?",
      back: "やあ、元気？/ やあ、調子は？",
      example_pt: "E aí, tudo bem? Faz tempo! — E aí, beleza? Que bom que vocês vieram!",
      example_ja: "やあ、元気？久しぶり！— やあ、調子は？来てくれてよかった！",
      notes: "E aí = 「それで」→ 挨拶の出だし。beleza = 美しさ → 「いい感じ？」。カジュアルな挨拶の定番",
    },
    {
      id: "2026-07-23-phrase-002",
      category: "phrase",
      subcategory: "greeting",
      front: "Como cê tá?",
      back: "調子どう？（= How are you?）",
      example_pt: "E aí, como cê tá? Faz tempo que não te vejo!",
      example_ja: "やあ、調子どう？久しぶりだね！",
      notes: "cê = você の口語短縮形。非常にカジュアル。書き言葉では使わない",
    },
    {
      id: "2026-07-23-phrase-003",
      category: "phrase",
      subcategory: "greeting",
      front: "Faz tempo!",
      back: "久しぶり！（= It's been a while! / Long time no see!）",
      example_pt: "Faz tempo que não nos vemos! Como vocês estão?",
      example_ja: "久しぶりだね！みんな元気？",
      notes: "faz tempo = 「時間が経った」。faz tempo que não te vejo = 会っていない時間が長い = 久しぶり",
    },
    {
      id: "2026-07-23-phrase-004",
      category: "phrase",
      subcategory: "arrival",
      front: "Eu cheguei atrasado, me desculpa.",
      back: "遅くなってすみません。（= Sorry I'm late.）",
      example_pt: "Desculpa o atraso. O trânsito estava um caos hoje.",
      example_ja: "遅れてすみません。今日は交通がひどかった。",
      notes: "me desculpa = ごめんなさい（カジュアル）。desculpa o atraso = 遅刻を詫びる（少しフォーマル）",
    },
    {
      id: "2026-07-23-phrase-005",
      category: "phrase",
      subcategory: "arrival",
      front: "Eu gastei muito tempo procurando um lugar pra estacionar.",
      back: "駐車場を探すのにすごく時間がかかった。",
      example_pt: "Desculpa o atraso, eu gastei muito tempo procurando um lugar pra estacionar.",
      example_ja: "遅れてごめん、駐車場を探すのにめちゃくちゃ時間かかった。",
      notes: "gastar tempo + gerúndio = 〜するのに時間を使う。lugar pra = 〜のための場所",
    },

    // ---- 会話に参加する（Como entrar na conversa）----------------

    {
      id: "2026-07-23-phrase-006",
      category: "phrase",
      subcategory: "conversation",
      front: "Você estava torcendo para quem?",
      back: "どのチームを応援してた？（= Who were you rooting for?）",
      example_pt: "E aí, você estava torcendo para quem no jogo de ontem?",
      example_ja: "ねえ、昨日の試合どのチーム応援してた？",
      notes: "torcer para = 〜を応援する。torcendo = 応援している（gerúndio）",
    },
    {
      id: "2026-07-23-phrase-007",
      category: "phrase",
      subcategory: "culture",
      front: "Brasileiros não gostam de argentinos no futebol, de jeito nenhum.",
      back: "ブラジル人はサッカーでアルゼンチンが絶対に好きじゃない。",
      example_pt: "No futebol, brasileiros não gostam de argentinos, de jeito nenhum.",
      example_ja: "サッカーにおいて、ブラジル人はアルゼンチンが断じて好きじゃない。",
      notes: "文化的背景：ブラジルとアルゼンチンは長年のライバル。de jeito nenhum = 絶対に〜しない",
    },

    // ---- 重要表現・文法ポイント ----------------------------------

    {
      id: "2026-07-23-vocab-009",
      category: "vocabulary",
      subcategory: "expression",
      front: "de jeito nenhum",
      back: "絶対に〜しない、断じて（= absolutely not / no way）",
      example_pt: "— Você torce para a Argentina? — De jeito nenhum!",
      example_ja: "「アルゼンチンを応援するの？」「絶対ないわ！」",
      notes: "jeito = 方法・やり方。「どんな方法でも」= 絶対に。否定の最強表現",
    },
    {
      id: "2026-07-23-vocab-010",
      category: "vocabulary",
      subcategory: "expression",
      front: "gastar tempo + gerúndio",
      back: "〜するのに時間を使う・費やす（= to spend time doing）",
      example_pt: "Gastei meia hora procurando estacionamento.",
      example_ja: "駐車場を探すのに30分費やした。",
      notes: "gastar = 使う・費やす。dinheiro も gastar：「Gastei muito dinheiro.」= お金をたくさん使った",
    },
    {
      id: "2026-07-23-vocab-011",
      category: "vocabulary",
      subcategory: "expression",
      front: "convidado（ser convidado）",
      back: "招待された（= to be invited）",
      example_pt: "Fomos convidados para um churrasco.",
      example_ja: "バーベキューに招待された。",
      notes: "convidar = 招待する。convidado = 招待された人・ゲスト。ser convidado = 招待される（受動態）",
    },
    {
      id: "2026-07-23-vocab-012",
      category: "vocabulary",
      subcategory: "word",
      front: "saudade",
      back: "久しぶりに会えた喜び・会いたかった気持ち（= longing / missed you）",
      example_pt: "Nossa, que saudade! Faz tempo que não te vejo.",
      example_ja: "うわー、会いたかった！久しぶりだね。",
      notes: "ポルトガル語で最も翻訳しにくい言葉の一つ。会えて嬉しい・会いたかったの感情",
    },

    // ---- チュラスコの状況・場面描写 ----------------------------

    {
      id: "2026-07-23-phrase-008",
      category: "phrase",
      subcategory: "situation",
      front: "チュラスコの状況を説明する表現",
      back: "Há cerca de dez pessoas. — 10人くらいいる\nAlguns são casais. — カップルもいる\nOutros levaram crianças. — 子連れもいる\nA carne ainda está na churrasqueira. — 肉はまだグリル上",
      example_pt: "As conversas mudam naturalmente — futebol, viagem, comida, trabalho.",
      example_ja: "会話は自然に変わっていく — サッカー、旅行、料理、仕事。",
      notes: "ninguém = 誰も〜しない。em seguida = その後・次に。enquanto = 〜している間に",
    },

    // ---- アルゼンチン・人種に関する表現 --------------------------

    {
      id: "2026-07-23-phrase-009",
      category: "phrase",
      subcategory: "conversation",
      front: "アルゼンチンのチームには黒人がいません。",
      back: "No time da Argentina não tem nenhum negro.",
      example_pt: "— Por que você não gosta da Argentina? — Porque no time deles não tem nenhum negro.",
      example_ja: "「なんでアルゼンチンが嫌いなの？」「チームに黒人が一人もいないから。」",
      notes: "negro = 黒人（ブラジルでは中立・尊重ある表現）。nenhum = 一人も〜ない（= not a single one）",
    },
    {
      id: "2026-07-23-phrase-010",
      category: "phrase",
      subcategory: "conversation",
      front: "アルゼンチンは人種差別が多い印象があります。",
      back: "Tenho a impressão de que a Argentina tem muito racismo.",
      example_pt: "Tenho a impressão de que a Argentina tem muito racismo. O time deles reflete isso.",
      example_ja: "アルゼンチンは人種差別が多い印象がある。チームの構成もそれを反映している。",
      notes: "racismo = 人種差別。tenho a impressão de que = 〜という印象がある（AULA 14で学習）",
    },

  ],
};
