window.LESSON_DATA_20260521 = {

  lesson: {
    id: "2026-05-21",
    date: "2026-05-21",
    title: "AULA 8: Emoção na Fala — Interjeições e Expressividade",
    theme: "感情表現・イントネーション",
  },

  cards: [

    // ---- 感情の語彙 -----------------------------------------------

    {
      id: "2026-05-21-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "incredulidade",
      back: "信じられないこと、不信（= disbelief / incredulity）",
      example_pt: "Nem acredito! = incredulidade",
      example_ja: "「信じられない！」= incredulidade（不信）",
      notes: "incredulo = 信じない。Nem acredito! がその代表表現",
    },
    {
      id: "2026-05-21-vocab-002",
      category: "vocabulary",
      subcategory: "word",
      front: "empolgação",
      back: "興奮、テンションが上がること（= excitement）",
      example_pt: "Que legal! Bom demais! = empolgação",
      example_ja: "「やばい！最高！」= empolgação（興奮）",
      notes: "empolgado = 興奮している。estar empolgado = テンション上がってる",
    },
    {
      id: "2026-05-21-vocab-003",
      category: "vocabulary",
      subcategory: "word",
      front: "alívio",
      back: "安堵、ほっとすること（= relief）",
      example_pt: "Ainda bem! = alívio",
      example_ja: "「よかった！」= alívio（安堵）",
      notes: "aliviado = ほっとした。Que alívio! = なんてほっとした！",
    },
    {
      id: "2026-05-21-vocab-004",
      category: "vocabulary",
      subcategory: "word",
      front: "frustração",
      back: "苛立ち、フラストレーション（= frustration）",
      example_pt: "Ah, não… = frustração",
      example_ja: "「あーもう…」= frustração（苛立ち）",
      notes: "frustrado = イライラした。Que frustração! = なんてフラストレーション！",
    },
    {
      id: "2026-05-21-vocab-005",
      category: "vocabulary",
      subcategory: "word",
      front: "admiração",
      back: "感嘆、驚嘆（= admiration / amazement）",
      example_pt: "Uau! Nossa senhora! = admiração",
      example_ja: "「うわー！すごい！」= admiração（感嘆）",
      notes: "admirar = 感心する・称賛する",
    },
    {
      id: "2026-05-21-vocab-006",
      category: "vocabulary",
      subcategory: "word",
      front: "vergonha",
      back: "恥ずかしさ（= shame / embarrassment）",
      example_pt: "Que vergonha! — How embarrassing!",
      example_ja: "「なんて恥ずかしい！」",
      notes: "estar com vergonha = 恥ずかしがっている。sem vergonha = 恥知らず",
    },
    {
      id: "2026-05-21-vocab-007",
      category: "vocabulary",
      subcategory: "word",
      front: "tenso",
      back: "緊張した、ハードだった（= tense / stressful）",
      example_pt: "Nossa, foi tenso aquele momento.",
      example_ja: "うわー、あの瞬間はマジで緊張した。",
      notes: "tensão = 緊張・張り詰めた状態。日本語の「キツかった」にも近い",
    },
    {
      id: "2026-05-21-vocab-008",
      category: "vocabulary",
      subcategory: "expression",
      front: "em cima da hora",
      back: "直前に、ギリギリに（= at the last minute）",
      example_pt: "Ele cancelou o compromisso em cima da hora.",
      example_ja: "彼は直前に予定をキャンセルした。",
      notes: "em cima = 上に / da hora = その時の。「その時間のギリギリ上」= 直前",
    },

    // ---- 感情別インテルジェイソン（感嘆詞）-----------------------

    {
      id: "2026-05-21-phrase-001",
      category: "phrase",
      subcategory: "reaction",
      front: "【驚き】の表現は？",
      back: "Nossa! / Caramba! / Sério?",
      example_pt: "Nossa, você cortou o cabelo!\nCaramba, que notícia!\nSério? Não sabia disso.",
      example_ja: "うわ、髪切ったの！\nやばい、そんなニュース！\nマジで？知らなかった。",
      notes: "強さ: Caramba > Nossa > Sério?（確認寄り）",
    },
    {
      id: "2026-05-21-phrase-002",
      category: "phrase",
      subcategory: "reaction",
      front: "【嬉しい・喜び】の表現は？",
      back: "Que bom! / Aí sim, hein!",
      example_pt: "Que bom que você veio!\nPassei na prova. — Aí sim, hein!",
      example_ja: "来てくれてよかった！\n試験受かった。— それだよ！やったね！",
      notes: "Aí sim, hein! = 「それだよ！」期待通りのことが起きたときの喜び",
    },
    {
      id: "2026-05-21-phrase-003",
      category: "phrase",
      subcategory: "reaction",
      front: "【信じられない】の表現は？",
      back: "Nem acredito!",
      example_pt: "Nem acredito, passei na prova!\nNem acredito que ele fez isso.",
      example_ja: "信じられない、試験受かった！\n彼がそんなことするなんて信じられない。",
      notes: "nem = even（否定強調）。「信じることさえできない」= 完全な驚き",
    },
    {
      id: "2026-05-21-phrase-004",
      category: "phrase",
      subcategory: "reaction",
      front: "【フラストレーション・がっかり】の表現は？",
      back: "Ah, não… / Ah não, não deu certo!",
      example_pt: "Ah, não… perdi o ônibus de novo.\nAh não, não deu certo!",
      example_ja: "あーもう…また乗り遅れた。\nあーだめだった！うまくいかなかった！",
      notes: "não deu certo = うまくいかなかった（deu = dar の過去形）",
    },
    {
      id: "2026-05-21-phrase-005",
      category: "phrase",
      subcategory: "reaction",
      front: "【興奮・テンション高め】の表現は？",
      back: "Que legal! / Bom demais! / Aí sim, hein!",
      example_pt: "Que legal, vai ter festa!\nBom demais! Adorei a ideia.",
      example_ja: "やばい、パーティーあるじゃん！\n最高すぎ！そのアイデア大好き。",
      notes: "demais = すぎる。Bom demais = 良すぎる → 最高！",
    },
    {
      id: "2026-05-21-phrase-006",
      category: "phrase",
      subcategory: "reaction",
      front: "【安堵・ほっとした】の表現は？",
      back: "Ainda bem!",
      example_pt: "Ainda bem que você chegou!\nNossa, você chegou! Ainda bem.",
      example_ja: "来てくれてよかった！\nうわ、来たね！よかった。",
      notes: "ainda = まだ / bem = よく → 「まだよかった」= 安堵。Thank goodness! に相当",
    },
    {
      id: "2026-05-21-phrase-007",
      category: "phrase",
      subcategory: "reaction",
      front: "【感嘆・すごい驚き】の表現は？",
      back: "Uau! / Nossa senhora!",
      example_pt: "Uau, que vista incrível!\nNossa senhora, que susto!",
      example_ja: "わー、なんて素晴らしい眺め！\nうわー、びっくりした！",
      notes: "Nossa senhora = 「聖母よ！」→ 強い感嘆・驚き。Nossa より強い",
    },

    // ---- 感情の強度スケール ---------------------------------------

    {
      id: "2026-05-21-phrase-008",
      category: "phrase",
      subcategory: "intensity",
      front: "「大変だった」を感情強度で言い分けると？",
      back: "弱 → 強\nFoi um pouco difícil.\nFoi bem difícil.\nFoi muito difícil.\nFoi difícil pra caramba!\nNossa, foi puxado!\nFoi tenso!\nQuase desisti!",
      example_pt: "",
      example_ja: "少し大変だった → かなり大変だった → めちゃ大変だった → 超ヤバかった → キツかった → 緊張した → もう諦めそうだった",
      notes: "ブラジル人は小さなことでも感情を強調して社会的つながりを作る",
    },

    // ---- 自然な構造（estruturas naturais）------------------------

    {
      id: "2026-05-21-vocab-009",
      category: "vocabulary",
      subcategory: "slang",
      front: "Tipo…",
      back: "なんか〜、みたいな（= like / kind of）",
      example_pt: "Eu tava, tipo, muito nervoso.",
      example_ja: "なんか、めちゃくちゃ緊張してたんだよね。",
      notes: "英語の \"like\" と同じ用法。話し言葉で頻出。考えながら話すときのクッション語",
    },
    {
      id: "2026-05-21-vocab-010",
      category: "vocabulary",
      subcategory: "slang",
      front: "Mano… / Cara…",
      back: "いやー、ちょっと（= Man… / Dude…）",
      example_pt: "Cara, você não vai acreditar.\nMano, foi demais!",
      example_ja: "ねえ、信じられないよ。\nいやー、やばすぎた！",
      notes: "mano = 兄貴（男性同士）/ cara = やつ。どちらも感嘆詞として文頭に使える",
    },
    {
      id: "2026-05-21-vocab-011",
      category: "vocabulary",
      subcategory: "expression",
      front: "Eu fiquei…",
      back: "〜な気持ちになった、〜になった（= I felt / I got）",
      example_pt: "Eu fiquei super feliz!\nNossa, fiquei nervoso na hora.",
      example_ja: "めちゃくちゃ嬉しかった！\nうわ、そのとき緊張した。",
      notes: "ficar + 形容詞 = 〜な状態になる（AULA 4 で学習済み）。感情表現の定番構造",
    },
    {
      id: "2026-05-21-vocab-012",
      category: "vocabulary",
      subcategory: "expression",
      front: "de verdade",
      back: "本当に、マジで（= really / for real）",
      example_pt: "Foi incrível, de verdade.\nEu gostei demais, de verdade.",
      example_ja: "本当に最高だった、マジで。\nマジで大好きだった。",
      notes: "文末に置いて感情を強調する。\"sério\" と似た用法",
    },
    {
      id: "2026-05-21-vocab-013",
      category: "vocabulary",
      subcategory: "slang",
      front: "Quase desisti!",
      back: "もう諦めそうだった！（= I almost gave up!）",
      example_pt: "Foi tão difícil, quase desisti!",
      example_ja: "本当に大変で、もう諦めそうだった！",
      notes: "desistir = 諦める。quase = ほとんど・あやうく",
    },

    // ---- シャドーイングフレーズ -----------------------------------

    {
      id: "2026-05-21-phrase-009",
      category: "phrase",
      subcategory: "shadowing",
      front: "Nossa, eu não esperava isso!",
      back: "うわー、それは予想外だった！",
      example_pt: "",
      example_ja: "",
      notes: "esperar = 期待する・待つ。não esperava = 予想していなかった（過去未完了）",
    },
    {
      id: "2026-05-21-phrase-010",
      category: "phrase",
      subcategory: "shadowing",
      front: "Sério? Nem acredito!",
      back: "マジで？信じられない！",
      example_pt: "",
      example_ja: "",
      notes: "驚き（Sério?）→ 不信（Nem acredito!）の自然な流れ。セットで使う",
    },
    {
      id: "2026-05-21-phrase-011",
      category: "phrase",
      subcategory: "shadowing",
      front: "Cara, foi muito engraçado!",
      back: "いやー、めちゃくちゃ面白かった！",
      example_pt: "",
      example_ja: "",
      notes: "engraçado = おかしい・面白い（笑える意味）。divertido = 楽しい・面白い（enjoyable）と区別",
    },
    {
      id: "2026-05-21-phrase-012",
      category: "phrase",
      subcategory: "shadowing",
      front: "Nossa, fiquei nervoso na hora.",
      back: "うわ、そのときめちゃ緊張した。",
      example_pt: "",
      example_ja: "",
      notes: "na hora = そのとき・その場で（= at that moment）",
    },

    // ---- 状況別リアクション ---------------------------------------

    {
      id: "2026-05-21-phrase-013",
      category: "phrase",
      subcategory: "reaction",
      front: "バスに乗り遅れたとき、何と言う？",
      back: "Nossa, que ruim, hein! / Ah, não…",
      example_pt: "Perdi o ônibus. — Nossa, que ruim, hein!",
      example_ja: "バス乗り遅れた。— うわー、最悪だね！",
      notes: "que ruim = 最悪・残念。hein? は同意・確認・感嘆の語尾",
    },
    {
      id: "2026-05-21-phrase-014",
      category: "phrase",
      subcategory: "reaction",
      front: "友達がコーヒー代を払ってくれたとき、何と言う？",
      back: "Nossa, não precisa não! / Valeu!",
      example_pt: "Vou pagar o seu café. — Nossa, não precisa não!",
      example_ja: "コーヒー払うよ。— うわー、いいよいいよ！",
      notes: "não precisa não = 「しなくていいよ」（não の重複で柔らかい否定）。Valeu = ありがとう（カジュアル）",
    },
    {
      id: "2026-05-21-phrase-015",
      category: "phrase",
      subcategory: "reaction",
      front: "スマホを落としたとき、何と言う？",
      back: "Nossa, eu não acredito! / Ah não, eu comprei ontem.",
      example_pt: "— Eu deixei o celular cair. — Nossa, eu não acredito! Ah não, eu comprei ontem.",
      example_ja: "スマホ落とした。— うわ、信じられない！あー、昨日買ったのに。",
      notes: "Ah não + 理由 で残念さを説明するナチュラルなパターン",
    },

  ],
};
