window.LESSON_DATA_20260715 = {

  lesson: {
    id: "2026-07-15",
    date: "2026-07-15",
    title: "AULA 10: Copa do Mundo 2026 — Vocabulário e Expressões do Futebol",
    theme: "サッカー表現・試合の語彙",
  },

  cards: [

    // ---- 試合前の表現（Antes do jogo）----------------------------

    {
      id: "2026-07-15-phrase-001",
      category: "phrase",
      subcategory: "pre-game",
      front: "Você acha que o Brasil leva essa?",
      back: "ブラジル取れると思う？（= Do you think Brazil will take it?）",
      example_pt: "— Você acha que o Brasil leva essa? — Estou confiante, mas não vai ser fácil.",
      example_ja: "「ブラジル取れると思う？」「自信はあるけど、楽じゃないよ。」",
      notes: "leva essa = それを持っていく = 勝つ。levar = 持っていく → 勝利を手にする",
    },
    {
      id: "2026-07-15-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "prorrogação",
      back: "延長戦（= extra time / overtime）",
      example_pt: "Esse jogo tem cara de prorrogação. — 45min × 2 + prorrogação: 15min + 15min",
      example_ja: "この試合、延長になりそう。— 前後半45分ずつのあと延長15分×2。",
      notes: "通常時間後の延長戦。その後にPK（pênaltis）がある",
    },
    {
      id: "2026-07-15-vocab-002",
      category: "vocabulary",
      subcategory: "word",
      front: "acréscimo",
      back: "アディショナルタイム（= stoppage time / added time）",
      example_pt: "Acréscimo de 6 minutos.",
      example_ja: "6分のアディショナルタイム。",
      notes: "試合中のロスタイム。prorrogação（延長戦）とは別物",
    },
    {
      id: "2026-07-15-phrase-002",
      category: "phrase",
      subcategory: "tournament",
      front: "トーナメントの段階をポルトガル語で言うと？",
      back: "Oitavas de final（16チーム）\nQuartas de final（8チーム）\nSemifinal（4チーム）\nFinal（2チーム）\nCampeão（優勝）/ Vice-campeão（準優勝）",
      example_pt: "Se jogar desse jeito, não passa das oitavas.",
      example_ja: "この調子じゃ、ベスト16で終わる。",
      notes: "Oitavas = 8分の1 = ベスト16。Quartas = 4分の1 = ベスト8",
    },
    {
      id: "2026-07-15-vocab-003",
      category: "vocabulary",
      subcategory: "word",
      front: "adversário",
      back: "対戦相手（= opponent）",
      example_pt: "Não dá para subestimar esse adversário.",
      example_ja: "この対戦相手を侮ることはできない。",
      notes: "subestimar = 過小評価する。Não dá para = 〜はできない",
    },
    {
      id: "2026-07-15-vocab-004",
      category: "vocabulary",
      subcategory: "word",
      front: "pressentimento",
      back: "予感（= feeling / premonition）",
      example_pt: "Estou com um bom pressentimento. Eu acho que hoje vai.",
      example_ja: "いい予感がする。今日いけると思う。",
      notes: "ter um pressentimento = 予感がする。bom pressentimento = 良い予感",
    },

    // ---- 試合中の反応（Durante o jogo）--------------------------

    {
      id: "2026-07-15-phrase-003",
      category: "phrase",
      subcategory: "during-game",
      front: "Que defesa absurda!",
      back: "なんて神セーブ！（= What an incredible save!）",
      example_pt: "Que defesa absurda! Esse goleiro tá salvando o time.",
      example_ja: "なんて神セーブ！このGKがチームを救っている。",
      notes: "absurda = 常識外れ・とんでもない。defesa = 守り・セーブ",
    },
    {
      id: "2026-07-15-phrase-004",
      category: "phrase",
      subcategory: "during-game",
      front: "Ele perdeu um gol feito!",
      back: "確実なゴールを外した！（= He missed a certain goal!）",
      example_pt: "Que pena! Ele perdeu um gol feito!",
      example_ja: "もったいない！ほぼ確実なゴールチャンスを逃した！",
      notes: "gol feito = 「できているゴール」= ほぼ確実なゴール。perdeu = 逃した",
    },
    {
      id: "2026-07-15-phrase-005",
      category: "phrase",
      subcategory: "during-game",
      front: "Isso não foi falta nunca!",
      back: "これは絶対ファールじゃない！（= That was never a foul!）",
      example_pt: "O juiz está marcando tudo. Isso não foi falta nunca!",
      example_ja: "審判は何でも取りすぎ。これは絶対ファールじゃない！",
      notes: "nunca = 決して〜ない（強調）。falta = ファール。o juiz = 審判",
    },
    {
      id: "2026-07-15-phrase-006",
      category: "phrase",
      subcategory: "during-game",
      front: "Tá carregando o time nas costas.",
      back: "一人でチームを背負っている。（褒め言葉）",
      example_pt: "O Vini tá carregando o time nas costas hoje.",
      example_ja: "今日のヴィニシウスは一人でチームを背負っている。",
      notes: "costas = 背中。carregar nas costas = 背負う。→ 褒め言葉！elogio（称賛）",
    },
    {
      id: "2026-07-15-phrase-007",
      category: "phrase",
      subcategory: "during-game",
      front: "Sumiu do jogo. / Tá apagado em campo.",
      back: "ゲームから消えた。/ ピッチで目立っていない。",
      example_pt: "Tá apagado em campo. Sumiu do jogo completamente.",
      example_ja: "ピッチで存在感がない。ゲームから完全に消えてしまった。",
      notes: "sumir = 消える。apagado = 影が薄い（消灯した）。どちらも「存在感のない選手」への批判",
    },
    {
      id: "2026-07-15-phrase-008",
      category: "phrase",
      subcategory: "during-game",
      front: "Tá dando um baile.",
      back: "圧倒している、翻弄している（= dancing circles around them）",
      example_pt: "Esse jogador tá dando um baile na defesa adversária.",
      example_ja: "あの選手、相手ディフェンスを翻弄しまくっている。",
      notes: "baile = ダンス・舞踏会。dar um baile = 「踊らせる」→ 相手を自在に操る",
    },

    // ---- ビハインド時（Quando o time está perdendo）--------------

    {
      id: "2026-07-15-phrase-009",
      category: "phrase",
      subcategory: "losing",
      front: "O jogo só acaba quando termina.",
      back: "試合は終わるまで終わらない。（= It ain't over till it's over.）",
      example_pt: "Ainda dá tempo. O jogo só acaba quando termina.",
      example_ja: "まだ時間がある。試合は終わるまで終わらないんだ。",
      notes: "ブラジルの定番サッカー格言。どんな状況でも諦めない精神",
    },
    {
      id: "2026-07-15-phrase-010",
      category: "phrase",
      subcategory: "losing",
      front: "O time precisa acordar!",
      back: "チームは目を覚まさないと！（= The team needs to wake up!）",
      example_pt: "Falta intensidade, falta entrosamento. O time precisa acordar!",
      example_ja: "強度も連携も足りない。チームは目を覚まさないと！",
      notes: "acordar = 目を覚ます。試合中に集中できていないチームへ使う表現",
    },
    {
      id: "2026-07-15-vocab-005",
      category: "vocabulary",
      subcategory: "word",
      front: "entrosamento",
      back: "チームワーク、連携（= team cohesion / chemistry）",
      example_pt: "Falta intensidade, falta entrosamento.",
      example_ja: "強度が足りない、連携も足りない。",
      notes: "entrosar = なじむ・連携する。選手同士のケミストリーを表す",
    },

    // ---- 試合後の分析（Pós-jogo）---------------------------------

    {
      id: "2026-07-15-vocab-006",
      category: "vocabulary",
      subcategory: "word",
      front: "placar",
      back: "スコア（= scoreboard / score）",
      example_pt: "O placar refletiu o que aconteceu em campo? / O placar foi enganoso.",
      example_ja: "スコアは試合の実態を反映していた？/ スコアは見た目通りではなかった。",
      notes: "enganoso = 欺くような・misleading。refletir = 反映する",
    },
    {
      id: "2026-07-15-vocab-007",
      category: "vocabulary",
      subcategory: "word",
      front: "destaque",
      back: "注目選手、際立つ存在（= standout / highlight）",
      example_pt: "Quem foi o destaque da partida?",
      example_ja: "試合のMVP・ベストプレーヤーは誰？",
      notes: "se destacar = 際立つ。「o destaque da partida」= 試合の最優秀選手",
    },
    {
      id: "2026-07-15-phrase-011",
      category: "phrase",
      subcategory: "post-game",
      front: "Houve uma queda de rendimento no segundo tempo.",
      back: "後半、パフォーマンスが落ちた。",
      example_pt: "Houve uma queda de rendimento no segundo tempo. Faltou eficiência nas finalizações.",
      example_ja: "後半パフォが落ちた。フィニッシュの精度も低かった。",
      notes: "queda = 低下。rendimento = パフォーマンス・出力。finalização = シュート",
    },
    {
      id: "2026-07-15-phrase-012",
      category: "phrase",
      subcategory: "post-game",
      front: "O time soube administrar a vantagem.",
      back: "チームはリードをうまく守り切った。",
      example_pt: "O time soube administrar a vantagem e venceu por 1 a 0.",
      example_ja: "チームはリードをうまく管理して1-0で勝った。",
      notes: "administrar a vantagem = リードを「管理する」。saber fazer = うまく〜できる",
    },
    {
      id: "2026-07-15-phrase-013",
      category: "phrase",
      subcategory: "post-game",
      front: "A equipe demonstrou maturidade emocional.",
      back: "チームは精神的な成熟さを示した。",
      example_pt: "A Argentina demonstrou maturidade emocional para reverter o placar.",
      example_ja: "アルゼンチンはスコアを覆す中で精神的成熟さを示した。",
      notes: "maturidade = 成熟。reverter o placar = スコアを逆転する",
    },

    // ---- サッカー慣用句（Expressões idiomáticas）-----------------

    {
      id: "2026-07-15-phrase-014",
      category: "phrase",
      subcategory: "idiom",
      front: "サッカー発の日常慣用句（6つ）",
      back: "pisar na bola = ミスをする\nbola para frente = 前に進む・切り替える\nvirar o jogo = 逆転する\nfazer cera = 時間を稼ぐ\ndar um chapéu = 欺く\nentrar em campo = 挑戦を始める",
      example_pt: "Meu colega pisou na bola comigo. / Bola para frente, vai melhorar!",
      example_ja: "同僚が私にミスをした。/ 前を向こう、きっとよくなる！",
      notes: "フィールド外の日常会話でも頻繁に使われる。覚えておくとブラジル人っぽくなる",
    },

    // ---- ポジション名（Posições）---------------------------------

    {
      id: "2026-07-15-vocab-008",
      category: "vocabulary",
      subcategory: "expression",
      front: "サッカーのポジション名（ポルトガル語）",
      back: "Goleiro（GK）\nDefesa（DF）\nLateral（SB）\nVolante（守備MF・ボランチ）\nMeio de campo（MF全般）\nAtacante（FW）\nPonta esquerda（左ウイング）\nPonta direita（右ウイング）",
      example_pt: "Vini Júnior é ponta esquerda. Rodrigo é volante.",
      example_ja: "ヴィニシウスは左ウイング。ロドリゴはボランチ。",
      notes: "volante = ブラジル独自の用語で守備的MF（ボランチ）を指す",
    },

  ],
};
