window.LESSON_DATA_20260715 = {

  lesson: {
    id: "2026-07-15",
    date: "2026-07-15",
    title: "AULA 13: Copa do Mundo — Análise Pós-jogo e Expressões Idiomáticas",
    theme: "試合後分析・サッカー慣用句・ポジション名",
  },

  cards: [

    // ---- 試合後の分析（Conversas pós-jogo）----------------------

    {
      id: "2026-07-15-phrase-001",
      category: "phrase",
      subcategory: "post-game",
      front: "O resultado foi justo?",
      back: "その結果は公平でしたか？（= Was the result fair?）",
      example_pt: "O resultado foi justo? O placar refletiu o que aconteceu em campo?",
      example_ja: "結果は公平だった？スコアは試合の実態を反映していた？",
      notes: "justo = 公平な。試合後の定番分析フレーズ",
    },
    {
      id: "2026-07-15-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "placar",
      back: "スコア（= scoreboard / score）",
      example_pt: "O placar refletiu o que aconteceu em campo? / O placar foi enganoso.",
      example_ja: "スコアは試合の実態を反映していた？/ スコアは見た目通りではなかった。",
      notes: "enganoso = 欺くような・misleading。refletir = 反映する",
    },
    {
      id: "2026-07-15-vocab-002",
      category: "vocabulary",
      subcategory: "word",
      front: "destaque",
      back: "注目選手、際立つ存在（= standout / highlight）",
      example_pt: "Quem foi o destaque da partida? Argentina e Egito → Messi.",
      example_ja: "試合のMVPは誰？アルゼンチン対エジプト→メッシ。",
      notes: "se destacar = 際立つ。「o destaque da partida」= 試合の最優秀選手",
    },
    {
      id: "2026-07-15-phrase-002",
      category: "phrase",
      subcategory: "post-game",
      front: "O que poderia ter sido feito diferente?",
      back: "何を変えることができたでしょうか？（= What could have been done differently?）",
      example_pt: "O que poderia ter sido feito diferente? O Brasil desperdiçou muitos ataques.",
      example_ja: "何を変えられたか？ブラジルは多くの攻撃を無駄にした。",
      notes: "poderia ter sido = 〜できていたかもしれない（仮定過去形）",
    },
    {
      id: "2026-07-15-phrase-003",
      category: "phrase",
      subcategory: "post-game",
      front: "O técnico acertou nas substituições?",
      back: "コーチの選手交代は適切でしたか？",
      example_pt: "Muitos jornalistas falam que o técnico não acertou nas substituições contra Noruega.",
      example_ja: "多くのジャーナリストはノルウェー戦で監督の采配は間違っていたと言う。",
      notes: "acertar = 当たる・的中する。substituição = 選手交代",
    },
    {
      id: "2026-07-15-vocab-003",
      category: "vocabulary",
      subcategory: "word",
      front: "desperdiçar",
      back: "無駄にする、チャンスを逃す（= to waste）",
      example_pt: "O Brasil desperdiçou muitos ataques.",
      example_ja: "ブラジルは多くの攻撃を無駄にした。",
      notes: "ataque = 攻撃。desperdiçar oportunidades = チャンスを逃す",
    },
    {
      id: "2026-07-15-phrase-004",
      category: "phrase",
      subcategory: "post-game",
      front: "O placar foi enganoso.",
      back: "スコアは実態を反映していなかった。（= The scoreline was misleading.）",
      example_pt: "O placar foi enganoso. O time que dominou o jogo acabou perdendo.",
      example_ja: "スコアは実態を反映していなかった。試合を支配したチームが結局負けた。",
      notes: "enganoso = 欺くような・見かけと違う。よくある試合分析フレーズ",
    },
    {
      id: "2026-07-15-phrase-005",
      category: "phrase",
      subcategory: "post-game",
      front: "A equipe demonstrou maturidade emocional.",
      back: "チームは精神的な成熟さを示した。",
      example_pt: "A Argentina demonstrou maturidade emocional para reverter o placar.",
      example_ja: "アルゼンチンはスコアを覆す中で精神的成熟さを示した。",
      notes: "maturidade = 成熟。reverter o placar = スコアを逆転する",
    },
    {
      id: "2026-07-15-phrase-006",
      category: "phrase",
      subcategory: "post-game",
      front: "Houve uma queda de rendimento no segundo tempo.",
      back: "後半、パフォーマンスが落ちた。",
      example_pt: "Houve uma queda de rendimento no segundo tempo. Faltou eficiência nas finalizações.",
      example_ja: "後半パフォが落ちた。フィニッシュの精度も低かった。",
      notes: "queda = 低下。rendimento = パフォーマンス。finalização = シュート・フィニッシュ",
    },
    {
      id: "2026-07-15-phrase-007",
      category: "phrase",
      subcategory: "post-game",
      front: "O time soube administrar a vantagem.",
      back: "チームはリードをうまく守り切った。",
      example_pt: "O time soube administrar a vantagem e venceu por 1 a 0.",
      example_ja: "チームはリードをうまく管理して1-0で勝った。",
      notes: "administrar a vantagem = リードを「管理する」。saber fazer = うまく〜できる",
    },
    {
      id: "2026-07-15-phrase-008",
      category: "phrase",
      subcategory: "post-game",
      front: "Faltou eficiência nas finalizações.",
      back: "フィニッシュの精度・効率が足りなかった。",
      example_pt: "Faltou eficiência nas finalizações do Brasil contra a Noruega.",
      example_ja: "ノルウェー戦でのブラジルはフィニッシュの効率が不足していた。",
      notes: "eficiência = 効率・精度。finalizações = シュート（複数形）",
    },

    // ---- サッカー慣用句（Expressões idiomáticas）-----------------

    {
      id: "2026-07-15-phrase-009",
      category: "phrase",
      subcategory: "idiom",
      front: "pisar na bola",
      back: "ミスをする（= to mess up / to drop the ball）",
      example_pt: "Meu colega pisou na bola comigo.",
      example_ja: "同僚が私に対してミスを犯した。",
      notes: "フィールド外の日常会話でも使う。comigo = 私に対して",
    },
    {
      id: "2026-07-15-phrase-010",
      category: "phrase",
      subcategory: "idiom",
      front: "bola para frente",
      back: "前に進む、切り替える（= move forward / keep going）",
      example_pt: "Depois do problema, bola para frente. Vai melhorar!",
      example_ja: "問題があっても、前に進もう。よくなるよ！",
      notes: "困難な状況の後に使う励ましの表現。tocar a vida = 人生を進める と同義",
    },
    {
      id: "2026-07-15-phrase-011",
      category: "phrase",
      subcategory: "idiom",
      front: "virar o jogo",
      back: "逆転する、状況をひっくり返す（= to turn the game around）",
      example_pt: "Ela conseguiu virar o jogo na entrevista de emprego.",
      example_ja: "彼女は就職面接で状況を逆転させた。",
      notes: "フィールド外でも使う。仕事・恋愛・人生の逆転に使える表現",
    },
    {
      id: "2026-07-15-phrase-012",
      category: "phrase",
      subcategory: "idiom",
      front: "fazer cera",
      back: "時間を稼ぐ（= to waste time / to kill time on purpose）",
      example_pt: "O time estava fazendo cera no final do jogo.",
      example_ja: "チームは試合終盤に時間を稼いでいた。",
      notes: "cera = ワックス（=磨くのに時間がかかる）→ わざと時間を無駄にする",
    },
    {
      id: "2026-07-15-phrase-013",
      category: "phrase",
      subcategory: "idiom",
      front: "サッカー発の日常慣用句（6つまとめ）",
      back: "pisar na bola = ミスする\nbola para frente = 前に進む\nvirar o jogo = 逆転する\nfazer cera = 時間を稼ぐ\ndar um chapéu = 欺く\nentrar em campo = 挑戦を始める",
      example_pt: "Marcar em cima = プレッシャーをかける。Jogar nas onze = 全力を出す。",
      example_ja: "marcar em cima = プレッシャーをかける。jogar nas onze = 全力でやる。",
      notes: "どれも日常会話・仕事・人間関係で使われる。覚えるとブラジル人らしくなる",
    },

    // ---- ポジション名（Posições）---------------------------------

    {
      id: "2026-07-15-vocab-004",
      category: "vocabulary",
      subcategory: "expression",
      front: "サッカーのポジション名（ポルトガル語）",
      back: "Goleiro（GK）\nDefesa（DF）\nLateral（SB）\nVolante（守備MF・ボランチ）\nMeio de campo（MF全般）\nAtacante / Centro-avante（CF）\nPonta esquerda（左ウイング）\nPonta direita（右ウイング）",
      example_pt: "Vini Júnior é ponta esquerda. Endrick é centro-avante.",
      example_ja: "ヴィニシウスは左ウイング。エンドリックはセンターFW。",
      notes: "volante = ブラジル独自の用語で守備的MF（ボランチ）を指す",
    },

  ],
};
