window.LESSON_DATA_20260430 = {

  lesson: {
    id: "2026-04-30",
    date: "2026-04-30",
    title: "AULA 6: Paradoxo Brasileiro — Suavização e Conectores Naturais",
    theme: "ブラジル文化・会話の自然さ",
  },

  cards: [

    // ---- スラング・口語表現 ----------------------------------------

    {
      id: "2026-04-30-vocab-001",
      category: "vocabulary",
      subcategory: "slang",
      front: "florear / floreia muito",
      back: "言葉を過剰に飾る・遠回しに言う",
      example_pt: "O brasileiro floreia muito, dessa maneira é bem diferente do francês.",
      example_ja: "ブラジル人はとても遠回しに言う。その点でフランス人とかなり違う。",
      notes: "flor = 花 → 花で飾る → 言葉を美しく飾り立てる。直接的な表現を避けるブラジルの文化的特徴",
    },
    {
      id: "2026-04-30-vocab-002",
      category: "vocabulary",
      subcategory: "slang",
      front: "ir com mais redondeza",
      back: "遠回しに言う、丸くまとめる",
      example_pt: "O brasileiro vai com mais redondeza do que falar diretamente.",
      example_ja: "ブラジル人は直接言うより遠回しに言う。",
      notes: "redondo = 丸い → 角を立てずに丸く言う。florear と似た意味",
    },
    {
      id: "2026-04-30-vocab-003",
      category: "vocabulary",
      subcategory: "slang",
      front: "sem zoeira",
      back: "冗談抜きで（= no joke / seriously）",
      example_pt: "Sem zoeira, esse cara é incrível.",
      example_ja: "冗談抜きで、あいつはすごい。",
      notes: "zoeira = 冗談・ふざけること。sem zoeira = without joking",
    },
    {
      id: "2026-04-30-vocab-004",
      category: "vocabulary",
      subcategory: "slang",
      front: "zoar / zoeira",
      back: "ふざける・からかう / 冗談・騒ぎ（= to joke / mess around）",
      example_pt: "Ele tá zoando comigo. / Que zoeira!",
      example_ja: "彼は私をからかっている。/ なんてふざけてるんだ！",
      notes: "zoar = ふざける・からかう・騒ぐ。zoeira = その名詞形",
    },
    {
      id: "2026-04-30-vocab-005",
      category: "vocabulary",
      subcategory: "slang",
      front: "coloroso",
      back: "温かみがある、情熱的（= warm / colourful personality）",
      example_pt: "O brasileiro é mais coloroso do que o europeu.",
      example_ja: "ブラジル人はヨーロッパ人より温かみがある。",
      notes: "color（色）から派生。感情が豊かで温かい人柄を表すインフォーマルな表現",
    },
    {
      id: "2026-04-30-vocab-006",
      category: "vocabulary",
      subcategory: "slang",
      front: "não tá nem aí",
      back: "全く気にしない、どうでもいい（= doesn't care at all）",
      example_pt: "O patrão não tá nem aí de saber se a funcionária consegue pagar as contas.",
      example_ja: "上司は従業員が家賃を払えるかどうかなんて全く気にしない。",
      notes: "\"não está nem aí\" の口語形。強い無関心を表す。英語の \"couldn't care less\"",
    },
    {
      id: "2026-04-30-vocab-007",
      category: "vocabulary",
      subcategory: "slang",
      front: "um monte de",
      back: "たくさんの（= a lot of / tons of）",
      example_pt: "Tem um monte de gente que se odeia nas redes sociais.",
      example_ja: "SNSにはお互いを憎んでいる人がたくさんいる。",
      notes: "monte = 山。\"uma montanha de\" より口語的でよく使われる",
    },
    {
      id: "2026-04-30-vocab-008",
      category: "vocabulary",
      subcategory: "slang",
      front: "meia dúzia",
      back: "半ダース（6人・6つ）、数人（= half a dozen）",
      example_pt: "Vai aparecer meia dúzia de cara pra ajudar a trocar o pneu.",
      example_ja: "タイヤ交換を手伝いに数人が現れる。",
      notes: "dúzia = 12（ダース）。meia = 半分。実際の6より「数名」のニュアンスで使われることも",
    },
    {
      id: "2026-04-30-vocab-009",
      category: "vocabulary",
      subcategory: "slang",
      front: "fofo / fofa",
      back: "かわいい、優しい（= cute / sweet）",
      example_pt: "Ela fala palavras fofas para o bebê.",
      example_ja: "彼女は赤ちゃんに優しい言葉をかける。",
      notes: "見た目のかわいさにも、言動の優しさにも使える。palavras fofas = 優しい言葉",
    },
    {
      id: "2026-04-30-vocab-010",
      category: "vocabulary",
      subcategory: "slang",
      front: "carente",
      back: "愛情に飢えている、孤独を感じている（= needy / lonely）",
      example_pt: "A gente também é muito carente, entende?",
      example_ja: "私たちはとても愛情に飢えてもいるんです、分かりますか？",
      notes: "carência = 欠乏・孤独感。日本語の「さみしがり」に近いニュアンス",
    },

    // ---- 重要単語 ------------------------------------------------

    {
      id: "2026-04-30-vocab-011",
      category: "vocabulary",
      subcategory: "word",
      front: "gentileza / gentil",
      back: "親切さ / 親切な（= kindness / kind）",
      example_pt: "Eu peguei a fama de ser um cara muito gentil.",
      example_ja: "私はとても親切な人という評判を得た。",
      notes: "gentileza brasileira = ブラジルの親切さ（このレッスンのテーマ）",
    },
    {
      id: "2026-04-30-vocab-012",
      category: "vocabulary",
      subcategory: "word",
      front: "raízes",
      back: "ルーツ、起源（= roots）",
      example_pt: "Mesmo ele tendo raízes libanesas, ele se sente brasileiro.",
      example_ja: "レバノン系のルーツを持っていても、彼はブラジル人だと感じている。",
      notes: "raiz（単数）= 根・ルーツ。raízes（複数）",
    },
    {
      id: "2026-04-30-vocab-013",
      category: "vocabulary",
      subcategory: "word",
      front: "selvagem",
      back: "野生の、荒々しい、残酷な（= wild / savage）",
      example_pt: "É um capitalismo muito selvagem, né?",
      example_ja: "とても弱肉強食な資本主義だよね？",
      notes: "capitalismo selvagem = 弱肉強食な資本主義。animais selvagens = 野生動物",
    },
    {
      id: "2026-04-30-vocab-014",
      category: "vocabulary",
      subcategory: "word",
      front: "freio",
      back: "ブレーキ、歯止め（= brake / restraint）",
      example_pt: "Um capitalismo que não tem muito freio.",
      example_ja: "あまり歯止めのない資本主義。",
      notes: "frear = ブレーキをかける。sem freio = 歯止めなく",
    },
    {
      id: "2026-04-30-vocab-015",
      category: "vocabulary",
      subcategory: "word",
      front: "contradição",
      back: "矛盾（= contradiction）",
      example_pt: "Tem essa contradição aqui no Brasil.",
      example_ja: "ブラジルにはこういう矛盾がある。",
      notes: "paradoxo（パラドックス）と近い意味で使われる",
    },
    {
      id: "2026-04-30-vocab-016",
      category: "vocabulary",
      subcategory: "word",
      front: "ódio",
      back: "憎しみ（= hate）",
      example_pt: "O brasileiro carrega um grande ódio e você vê nas redes sociais.",
      example_ja: "ブラジル人は大きな憎しみを抱えていて、SNSで見られる。",
      notes: "odiar = 憎む。ódio ↔ amor（愛）。このレッスンの「paradoxo」の核心",
    },
    {
      id: "2026-04-30-vocab-017",
      category: "vocabulary",
      subcategory: "word",
      front: "carinho",
      back: "愛情、思いやり（= affection / care）",
      example_pt: "E ao mesmo tempo esse carinho todo, esse amor todo.",
      example_ja: "そして同時に、この愛情全て、この愛全て。",
      notes: "ter carinho por alguém = 誰かへの愛情を持つ。ódio（憎しみ）と対比されるこのレッスンのキーワード",
    },
    {
      id: "2026-04-30-vocab-018",
      category: "vocabulary",
      subcategory: "word",
      front: "patrão / patroa",
      back: "上司、オーナー（= boss / employer）",
      example_pt: "O patrão não tá nem aí de saber se a funcionária consegue pagar as contas.",
      example_ja: "上司は従業員が家賃を払えるかどうか全く気にしない。",
      notes: "funcionário/funcionária = 従業員。patrão ↔ funcionário",
    },
    {
      id: "2026-04-30-vocab-019",
      category: "vocabulary",
      subcategory: "word",
      front: "devolver",
      back: "返す、返礼する（= to return / give back）",
      example_pt: "Ele quer devolver o carinho que recebeu no Brasil.",
      example_ja: "彼はブラジルで受け取った愛情を返したいと思っている。",
      notes: "dar = 与える / devolver = 返す。de（戻す方向）+ volver（回す）",
    },
    {
      id: "2026-04-30-vocab-020",
      category: "vocabulary",
      subcategory: "word",
      front: "pneu furado",
      back: "パンクしたタイヤ（= flat tire）",
      example_pt: "O cara tem um pneu furado, vai aparecer meia dúzia de cara pra ajudar.",
      example_ja: "タイヤがパンクしていると、手伝いに数人が現れる。",
      notes: "pneu = タイヤ / furado = 穴の開いた（furar = 穴を開ける）",
    },
    {
      id: "2026-04-30-vocab-021",
      category: "vocabulary",
      subcategory: "expression",
      front: "pegar a fama de",
      back: "〜という評判を得る（= to gain a reputation for）",
      example_pt: "Eu peguei a fama de ser um cara muito gentil.",
      example_ja: "私はとても親切な人という評判を得た。",
      notes: "fama = 評判・名声。pegar fama boa = 良い評判を得る / fama ruim = 悪い評判",
    },
    {
      id: "2026-04-30-vocab-022",
      category: "vocabulary",
      subcategory: "expression",
      front: "se preocupar com",
      back: "〜を心配する、気にかける（= to care about / worry about）",
      example_pt: "As pessoas se preocupam com você aqui.",
      example_ja: "ここでは人々があなたのことを気にかけてくれる。",
      notes: "preocupado = 心配している。se preocupar com ～ = ～について心配する",
    },
    {
      id: "2026-04-30-vocab-023",
      category: "vocabulary",
      subcategory: "expression",
      front: "soar + 形容詞",
      back: "〜に聞こえる・〜な印象を与える（= to sound / seem + adj）",
      example_pt: "Isso pode soar muito rude para um brasileiro.\nEle soa muito gentil.",
      example_ja: "それはブラジル人にはとても失礼に聞こえる。\n彼はとても親切そうに見える。",
      notes: "soar = 音を出す → 転じて「〜な印象を与える」。英語の sound/seem に相当",
    },

    // ---- フレーズ ------------------------------------------------

    {
      id: "2026-04-30-phrase-001",
      category: "phrase",
      subcategory: "culture",
      front: "Isso é o paradoxo do Brasil.",
      back: "これがブラジルのパラドックスだ。",
      example_pt: "É uma mistura de sentimentos. Isso é o paradoxo do Brasil.",
      example_ja: "感情の混合だ。これがブラジルのパラドックスだ。",
      notes: "このレッスンの中心テーマ。ブラジル社会の矛盾を表す",
    },
    {
      id: "2026-04-30-phrase-002",
      category: "phrase",
      subcategory: "culture",
      front: "Mesmo ele tendo raízes libanesas, ele considera o coração dele brasileiro.",
      back: "レバノン系のルーツを持っていても、彼は自分の心はブラジル人だと思っている。",
      example_pt: "",
      example_ja: "",
      notes: "mesmo + gerúndio = 〜であっても（譲歩）。mesmo ele tendo = even though he has",
    },
    {
      id: "2026-04-30-phrase-003",
      category: "phrase",
      subcategory: "culture",
      front: "Por um lado... mas por outro lado...",
      back: "一方では…しかし他方では…",
      example_pt: "Por um lado, a sociedade é muito rude. Mas por outro lado, as pessoas são muito gentis.",
      example_ja: "一方では、社会はとても荒々しい。しかし他方では、人々はとても親切だ。",
      notes: "このレッスンの核心構造。paradoxoを説明するときの定番パターン",
    },

    // ---- 接続詞・ディスコースマーカー ----------------------------

    {
      id: "2026-04-30-connector-001",
      category: "connector",
      subcategory: "cause",
      front: "por conta disso",
      back: "そのせいで、そのわけで（= because of that / that's why）",
      example_pt: "Ele morou no Brasil. Por conta disso, ele é muito gentil.",
      example_ja: "彼はブラジルに住んでいた。そのせいで、彼はとても親切だ。",
      notes: "por isso と同じ意味だが、より口語的で強調感がある",
    },
    {
      id: "2026-04-30-connector-002",
      category: "connector",
      subcategory: "contrast",
      front: "só que",
      back: "でも、ただし（= but / however）口語的",
      example_pt: "Ele parece insensível. Só que ele vai te ajudar a trocar o pneu.",
      example_ja: "彼は無神経に見える。でも、タイヤ交換を手伝ってくれる。",
      notes: "mas より口語的。会話で非常によく使われる逆接。\"só que\" の後は予想外の展開が来ることが多い",
    },
    {
      id: "2026-04-30-connector-003",
      category: "connector",
      subcategory: "addition",
      front: "ao mesmo tempo",
      back: "同時に（= at the same time）",
      example_pt: "Tem ódio e ao mesmo tempo tem muito carinho.",
      example_ja: "憎しみがある。そして同時に、たくさんの愛情もある。",
      notes: "対比する2つの事実を同時に述べるときに使う",
    },
    {
      id: "2026-04-30-connector-004",
      category: "connector",
      subcategory: "manner",
      front: "dessa maneira",
      back: "このように、このやり方で（= in this way）",
      example_pt: "Faça dessa maneira. / Dessa maneira, é diferente do japonês.",
      example_ja: "このようにやってください。/ このように、日本人とは違う。",
      notes: "desse = \"de esse\"（この）。dessa maneira = このやり方で。de outra maneira = 別の方法で",
    },
    {
      id: "2026-04-30-connector-005",
      category: "connector",
      subcategory: "concession",
      front: "mesmo + gerúndio",
      back: "〜であっても（= even though / even if）",
      example_pt: "Mesmo morando no exterior, ele fala português.\nMesmo ele tendo raízes libanesas…",
      example_ja: "海外に住んでいても、彼はポルトガル語を話す。\n彼はレバノン系のルーツを持っていても…",
      notes: "譲歩の構文。mesmo + 動詞のgerúndio（〜ing形）。英語の \"even though\" に相当",
    },
    {
      id: "2026-04-30-vocab-024",
      category: "vocabulary",
      subcategory: "word",
      front: "gerúndio（ジェルンジオ）とは？",
      back: "動詞の〜ing形。語尾: -ar→ando / -er→endo / -ir→indo",
      example_pt: "falar → falando（話している）\ncomer → comendo（食べている）\nter → tendo（持っている）",
      example_ja: "Estou trabalhando. → 今働いています。\nEle saiu sorrindo. → 笑いながら出た。\nMesmo tendo raízes… → 〜ルーツを持っていても",
      notes: "①進行形 estar + gerúndio ②〜しながら ③mesmo + gerúndio（〜であっても）の3用法が重要",
    },

  ],
};
