window.LESSON_DATA_20260423 = {

  lesson: {
    id: "2026-04-23",
    date: "2026-04-23",
    title: "AULA 5: Microexpressões e Vocabulário da Casa",
    theme: "リアクション表現・家",
  },

  cards: [

    // ---- マイクロ表現（リアクション）------------------------------

    {
      id: "2026-04-23-vocab-001",
      category: "vocabulary",
      subcategory: "expression",
      front: "Nossa!",
      back: "うわっ！すごい！（驚き・感嘆）",
      example_pt: "Nossa, que casa enorme!",
      example_ja: "うわっ、なんて大きい家！",
      notes: "ブラジル人が最も頻繁に使うリアクション表現のひとつ。驚き・感動どちらにも使える",
    },
    {
      id: "2026-04-23-vocab-002",
      category: "vocabulary",
      subcategory: "slang",
      front: "Cê tá louco!",
      back: "うそでしょ！正気？（驚き・冗談っぽく）",
      example_pt: "Cê tá louco! Pagou 500 mil reais por isso?",
      example_ja: "うそでしょ！それに50万レアル払ったの？",
      notes: "\"Você está louco\" の口語短縮形。louco = 狂った。驚きを強調するカジュアルな表現",
    },
    {
      id: "2026-04-23-vocab-003",
      category: "vocabulary",
      subcategory: "expression",
      front: "Que loucura!",
      back: "なんてこった！クレイジー！",
      example_pt: "Que loucura, ele comprou uma mansão!",
      example_ja: "なんてこった、彼、マンションを買ったんだって！",
      notes: "loucura = 狂気・非常識なこと。Nossa! と組み合わせて使うことも多い",
    },
    {
      id: "2026-04-23-vocab-004",
      category: "vocabulary",
      subcategory: "expression",
      front: "Que legal!",
      back: "いいね！すごい！（肯定的な驚き）",
      example_pt: "Que legal, você vai morar em Tóquio!",
      example_ja: "いいね、東京に住むんだって！",
      notes: "legal = かっこいい・いい（ブラジルスラング）。good to know のニュアンスも含む",
    },
    {
      id: "2026-04-23-vocab-005",
      category: "vocabulary",
      subcategory: "expression",
      front: "Sério? / É sério?",
      back: "本当に？マジで？（= really?）",
      example_pt: "Sério? Ele tem uma mansão com 4 banheiros?",
      example_ja: "マジで？彼、バスルーム4つある豪邸を持ってるの？",
      notes: "「é verdade?」（本当？）と同じ意味で使える。驚きの確認表現",
    },
    {
      id: "2026-04-23-vocab-006",
      category: "vocabulary",
      subcategory: "expression",
      front: "Pois é…",
      back: "そうなんだよね…（同意・共感・やれやれ感）",
      example_pt: "Pois é, eu tentei fazer a prova mas não passei.",
      example_ja: "そうなんだよね、試験受けたんだけど受からなかった。",
      notes: "同意・共感・ため息が混ざった表現。「まあ、そうですよね」的なニュアンス",
    },
    {
      id: "2026-04-23-vocab-007",
      category: "vocabulary",
      subcategory: "expression",
      front: "Aham.",
      back: "うんうん、なるほど（= I see / uh-huh）",
      example_pt: "Aham, entendi.",
      example_ja: "うんうん、分かった。",
      notes: "相槌。会話を続けさせる「聞いてますよ」サイン。Entendi. よりカジュアル",
    },
    {
      id: "2026-04-23-vocab-008",
      category: "vocabulary",
      subcategory: "expression",
      front: "Imagino.",
      back: "想像できる。そうだろうね。（= I can imagine）",
      example_pt: "— Foi muito difícil. — Imagino.",
      example_ja: "「すごく大変だったよ。」「そうだろうね。」",
      notes: "相手の状況に共感する表現。日本語の「大変だったね」に近いニュアンスも出せる",
    },
    {
      id: "2026-04-23-vocab-009",
      category: "vocabulary",
      subcategory: "expression",
      front: "Entendi.",
      back: "分かった。理解した。（= I understand / got it）",
      example_pt: "Entendi, vou fazer isso amanhã.",
      example_ja: "分かった、明日やります。",
      notes: "entender（理解する）の過去形。英語の \"got it\" に相当",
    },

    // ---- 家の語彙 ------------------------------------------------

    {
      id: "2026-04-23-vocab-010",
      category: "vocabulary",
      subcategory: "word",
      front: "mansão",
      back: "豪邸、マンション（大きくて豪華な家）",
      example_pt: "Casas gigantes são chamadas de mansão.",
      example_ja: "大きくて豪華な家は「マンション」と呼ばれる。",
      notes: "英語の「mansion」と同じ。日本語の「マンション（集合住宅）」とは違う",
    },
    {
      id: "2026-04-23-vocab-011",
      category: "vocabulary",
      subcategory: "word",
      front: "sobrado",
      back: "2階建ての家",
      example_pt: "Moro em um sobrado com 3 quartos.",
      example_ja: "3寝室の2階建て家に住んでいる。",
      notes: "andar = 階。sobrado = 2階建て一軒家（集合住宅ではない）",
    },
    {
      id: "2026-04-23-vocab-012",
      category: "vocabulary",
      subcategory: "word",
      front: "andar",
      back: "階（= floor）",
      example_pt: "A casa tem 2 andares.",
      example_ja: "その家は2階建てだ。",
      notes: "2 andares = 2階建て / 1º andar = 1階（ブラジルでは地上階）",
    },
    {
      id: "2026-04-23-vocab-013",
      category: "vocabulary",
      subcategory: "word",
      front: "quarto",
      back: "寝室（= bedroom）",
      example_pt: "A casa tem 3 quartos e 4 banheiros.",
      example_ja: "その家には寝室が3つ、バスルームが4つある。",
      notes: "quarto = 部屋・寝室両方に使う",
    },
    {
      id: "2026-04-23-vocab-014",
      category: "vocabulary",
      subcategory: "word",
      front: "cozinha",
      back: "台所、キッチン（= kitchen）",
      example_pt: "A cozinha é grande e moderna.",
      example_ja: "キッチンは広くて近代的だ。",
      notes: "",
    },
    {
      id: "2026-04-23-vocab-015",
      category: "vocabulary",
      subcategory: "word",
      front: "banheiro",
      back: "バスルーム、トイレ（= bathroom）",
      example_pt: "Tem 4 banheiros na mansão.",
      example_ja: "豪邸にはバスルームが4つある。",
      notes: "ブラジルではトイレとシャワーが同室が一般的",
    },
    {
      id: "2026-04-23-vocab-016",
      category: "vocabulary",
      subcategory: "word",
      front: "sala",
      back: "リビング、部屋（= living room / room）",
      example_pt: "A casa tem 2 salas — uma de estar e uma de jantar.",
      example_ja: "その家にはリビングと食堂の2つの部屋がある。",
      notes: "sala de estar = リビング / sala de jantar = ダイニング",
    },
    {
      id: "2026-04-23-vocab-017",
      category: "vocabulary",
      subcategory: "word",
      front: "escritório",
      back: "書斎、オフィス（= office / study room）",
      example_pt: "Trabalho no meu escritório em casa.",
      example_ja: "自宅の書斎で仕事している。",
      notes: "在宅勤務が増えて「escritório em casa（ホームオフィス）」という表現も頻出",
    },
    {
      id: "2026-04-23-vocab-018",
      category: "vocabulary",
      subcategory: "word",
      front: "garagem",
      back: "ガレージ（= garage）",
      example_pt: "A garagem tem espaço para 2 carros.",
      example_ja: "ガレージには車2台分のスペースがある。",
      notes: "",
    },
    {
      id: "2026-04-23-vocab-019",
      category: "vocabulary",
      subcategory: "word",
      front: "quintal",
      back: "裏庭、庭（= backyard）",
      example_pt: "As crianças brincam no quintal.",
      example_ja: "子供たちが庭で遊んでいる。",
      notes: "jardim = 前庭 / quintal = 裏庭が一般的な区別",
    },
    {
      id: "2026-04-23-vocab-020",
      category: "vocabulary",
      subcategory: "word",
      front: "perto / longe",
      back: "近い / 遠い（= close / far）",
      example_pt: "A escola é perto. O aeroporto é longe.",
      example_ja: "学校は近い。空港は遠い。",
      notes: "perto de ～ = ～の近くに / longe de ～ = ～から遠くに",
    },
    {
      id: "2026-04-23-vocab-021",
      category: "vocabulary",
      subcategory: "expression",
      front: "ter um sonho",
      back: "夢を持つ・夢がある（= have a dream）",
      example_pt: "Tenho um sonho de ter uma casa com quintal.",
      example_ja: "庭付きの家を持つ夢がある。",
      notes: "sonho = 夢。ter = 持つ。Tenho um sonho de + 動詞原形",
    },
    {
      id: "2026-04-23-vocab-022",
      category: "vocabulary",
      subcategory: "expression",
      front: "contrato da casa",
      back: "賃貸契約書（= rental contract / lease）",
      example_pt: "Assino o contrato da casa amanhã.",
      example_ja: "明日、賃貸契約書にサインする。",
      notes: "assinar o contrato = 契約書にサインする",
    },
    {
      id: "2026-04-23-vocab-023",
      category: "vocabulary",
      subcategory: "expression",
      front: "renovar o contrato",
      back: "契約を更新する（= renew the contract）",
      example_pt: "Vou renovar o contrato ou procurar outra casa.",
      example_ja: "契約を更新するか、別の家を探すつもりだ。",
      notes: "対義語: não renovar o contrato = 契約を更新しない",
    },

    // ---- 大学の専攻 -----------------------------------------------

    {
      id: "2026-04-23-vocab-024",
      category: "vocabulary",
      subcategory: "word",
      front: "Medicina",
      back: "医学（いがく）",
      example_pt: "Ela estuda Medicina e quer ser cirurgiã.",
      example_ja: "彼女は医学を学んでいて、外科医になりたいと思っている。",
      notes: "médico/médica = 医者。ブラジルで最も競争率の高い専攻のひとつ",
    },
    {
      id: "2026-04-23-vocab-025",
      category: "vocabulary",
      subcategory: "word",
      front: "Administração",
      back: "経営学（けいえいがく）",
      example_pt: "Fiz Administração e trabalho numa empresa grande.",
      example_ja: "経営学を学んで、大きな会社で働いている。",
      notes: "ブラジルで最も学生数が多い専攻。administrador = 経営者・管理職",
    },
    {
      id: "2026-04-23-vocab-026",
      category: "vocabulary",
      subcategory: "word",
      front: "Direito",
      back: "法学（ほうがく）",
      example_pt: "Ele estudou Direito e virou advogado.",
      example_ja: "彼は法学を学んで弁護士になった。",
      notes: "advogado = 弁護士。direito = 権利・法 の二つの意味がある",
    },
    {
      id: "2026-04-23-vocab-027",
      category: "vocabulary",
      subcategory: "expression",
      front: "Engenharia Civil",
      back: "土木工学（どぼくこうがく）",
      example_pt: "Engenharia Civil forma engenheiros que constroem pontes e edifícios.",
      example_ja: "土木工学は橋や建物を建てるエンジニアを育てる。",
      notes: "engenheiro civil = 土木エンジニア。ブラジルの建設ブームで需要が高い",
    },
    {
      id: "2026-04-23-vocab-028",
      category: "vocabulary",
      subcategory: "expression",
      front: "Ciência da Computação",
      back: "情報科学（じょうほうかがく）",
      example_pt: "Ele fez Ciência da Computação e trabalha com inteligência artificial.",
      example_ja: "彼は情報科学を学んで、AIの仕事をしている。",
      notes: "= Computer Science。Sistemas de Informação より理論・研究寄り",
    },
    {
      id: "2026-04-23-vocab-029",
      category: "vocabulary",
      subcategory: "word",
      front: "Enfermagem",
      back: "看護学（かんごがく）",
      example_pt: "Minha irmã faz Enfermagem e trabalha num hospital.",
      example_ja: "妹は看護学を学んで、病院で働いている。",
      notes: "enfermeiro/enfermeira = 看護師",
    },
    {
      id: "2026-04-23-vocab-030",
      category: "vocabulary",
      subcategory: "word",
      front: "Pedagogia",
      back: "教育学（きょういくがく）",
      example_pt: "Ela fez Pedagogia e dá aula para crianças.",
      example_ja: "彼女は教育学を学んで、子供たちに授業をしている。",
      notes: "pedagogo/pedagoga = 教育者。professor = 教師（より一般的な呼び方）",
    },
    {
      id: "2026-04-23-vocab-031",
      category: "vocabulary",
      subcategory: "expression",
      front: "Engenharia Mecânica",
      back: "機械工学（きかいこうがく）",
      example_pt: "Engenharia Mecânica é muito concorrida nas universidades.",
      example_ja: "機械工学は大学でとても競争率が高い。",
      notes: "mecânico = 機械の・整備士。エンジニア系の代表格",
    },
    {
      id: "2026-04-23-vocab-032",
      category: "vocabulary",
      subcategory: "expression",
      front: "Sistemas de Informação",
      back: "情報システム（じょうほうシステム）",
      example_pt: "Sistemas de Informação é mais voltado para o mercado de trabalho.",
      example_ja: "情報システムはより就職市場向けの専攻だ。",
      notes: "Ciência da Computação より実践・ビジネス寄り。IT系で両方よく出る",
    },
    {
      id: "2026-04-23-vocab-033",
      category: "vocabulary",
      subcategory: "word",
      front: "Nutrição",
      back: "栄養学（えいようがく）",
      example_pt: "Ela estuda Nutrição porque quer ajudar pessoas a comer melhor.",
      example_ja: "彼女は人々がより良い食事をとれるように栄養学を学んでいる。",
      notes: "nutricionista = 栄養士。saúde（健康）への意識が高いブラジルで人気",
    },

    // ---- フレーズ ------------------------------------------------

    {
      id: "2026-04-23-phrase-001",
      category: "phrase",
      subcategory: "housing",
      front: "A casa tem 3 quartos, 1 cozinha, 4 banheiros, 2 salas e 2 escritórios.",
      back: "その家には寝室3、キッチン1、バスルーム4、リビング2、書斎2がある。",
      example_pt: "",
      example_ja: "",
      notes: "家の間取りを説明するテンプレート文",
    },
    {
      id: "2026-04-23-phrase-002",
      category: "phrase",
      subcategory: "housing",
      front: "Eu alugo uma casa.",
      back: "私は家を借りている。",
      example_pt: "Eu alugo uma casa perto do trabalho.",
      example_ja: "職場の近くの家を借りている。",
      notes: "alugar = 借りる・貸す。主語によって意味が変わる",
    },

    // ---- リアクション練習カード -----------------------------------

    {
      id: "2026-04-23-phrase-003",
      category: "phrase",
      subcategory: "reaction",
      front: "「友達が宝くじに当たった」と聞いたとき、何と言う？",
      back: "Nossa! / Sério? / Que loucura! / Cê tá louco!",
      example_pt: "— Meu amigo ganhou na loteria! — Nossa! Sério? Que loucura!",
      example_ja: "「友達が宝くじ当たった！」「うわっ！マジで？なんてこった！」",
      notes: "リアクションは組み合わせて使うと自然。重要：反応の速さが流暢さに見える",
    },
    {
      id: "2026-04-23-phrase-004",
      category: "phrase",
      subcategory: "reaction",
      front: "「仕事がとても大変だった」と聞いたとき、何と言う？",
      back: "Pois é… / Imagino. / Que difícil!",
      example_pt: "— Foi um dia muito difícil. — Pois é… Imagino. Que difícil!",
      example_ja: "「今日すごく大変だったよ。」「そうだよね…想像できる。大変だったね。」",
      notes: "共感のリアクション。Imagino. は特に気持ちに寄り添う",
    },

  ],
};
