window.LESSON_DATA_20260401 = {

  lesson: {
    id: "2026-04-01",
    date: "2026-04-01",
    title: "AULA 3: Viagens Inteligentes e Econômicas",
    theme: "旅行・節約",
  },

  cards: [

    // ---- 単語・表現 ------------------------------------------------

    {
      id: "2026-04-01-vocab-001",
      category: "vocabulary",
      subcategory: "slang",
      front: "grana",
      back: "お金（スラング）",
      example_pt: "Ela gastou toda a grana.",
      example_ja: "彼女はお金を全部使ってしまった。",
      notes: "口語的。日常会話でよく使われる",
    },
    {
      id: "2026-04-01-vocab-002",
      category: "vocabulary",
      subcategory: "slang",
      front: "torrar grana",
      back: "お金を使いまくる、浪費する",
      example_pt: "Ele torrou grana pra caramba nas férias.",
      example_ja: "彼は休暇中にめちゃくちゃお金を使いまくった。",
      notes: "torrar = 焦がす → 転じて「溶かす」",
    },
    {
      id: "2026-04-01-vocab-003",
      category: "vocabulary",
      subcategory: "slang",
      front: "pra caramba",
      back: "すごく、めちゃくちゃ（強調）",
      example_pt: "Está calor pra caramba hoje!",
      example_ja: "今日はめちゃくちゃ暑い！",
      notes: "強調表現。torrar granaと一緒に使われることが多い",
    },
    {
      id: "2026-04-01-vocab-004",
      category: "vocabulary",
      subcategory: "expression",
      front: "baixa temporada",
      back: "オフシーズン",
      example_pt: "Na baixa temporada, os preços caem pela metade.",
      example_ja: "オフシーズンには値段が半額になる。",
      notes: "対義語: alta temporada（ハイシーズン）",
    },
    {
      id: "2026-04-01-vocab-005",
      category: "vocabulary",
      subcategory: "expression",
      front: "alta temporada",
      back: "ハイシーズン",
      example_pt: "Na alta temporada, tudo fica mais caro.",
      example_ja: "ハイシーズンには何もかも高くなる。",
      notes: "対義語: baixa temporada（オフシーズン）",
    },
    {
      id: "2026-04-01-vocab-006",
      category: "vocabulary",
      subcategory: "word",
      front: "ostentação",
      back: "見せびらかし、贅沢",
      example_pt: "Ele gosta de ostentação.",
      example_ja: "彼は見せびらかしが好きだ。",
      notes: "",
    },
    {
      id: "2026-04-01-vocab-007",
      category: "vocabulary",
      subcategory: "expression",
      front: "valer a pena",
      back: "〜の価値がある、割に合う",
      example_pt: "Vale a pena viajar na baixa temporada.",
      example_ja: "オフシーズンに旅行する価値がある。",
      notes: "「it's worth it」に相当する表現",
    },
    {
      id: "2026-04-01-vocab-007b",
      category: "vocabulary",
      subcategory: "expression",
      front: "valer a pena の構造は？",
      back: "valer（価値がある）+ a（〜を）+ pena（苦労・痛み）\n→「苦労に見合う価値がある」",
      example_pt: "Não vale a pena gastar tanto.",
      example_ja: "そんなに使う価値はない。（否定形: não vale a pena）",
      notes: "vale = valer の三人称単数現在形（it is worth）",
    },
    {
      id: "2026-04-01-vocab-008",
      category: "vocabulary",
      subcategory: "expression",
      front: "pegar promoção",
      back: "セール・割引をゲットする",
      example_pt: "Consegui pegar uma promoção ótima de passagem.",
      example_ja: "とても良いチケットの割引をゲットできた。",
      notes: "promoção = プロモーション、割引",
    },
    {
      id: "2026-04-01-vocab-008b",
      category: "vocabulary",
      subcategory: "word",
      front: "ótimo / ótima",
      back: "素晴らしい、最高の（excellent / great）",
      example_pt: "Consegui pegar uma promoção ótima de passagem.",
      example_ja: "チケットの最高の割引をゲットできた。",
      notes: "bom（良い）の絶対最上級。名詞の性に合わせて ótimo（男）/ ótima（女）。感嘆詞として「Ótimo!」も頻出",
    },
    {
      id: "2026-04-01-vocab-009",
      category: "vocabulary",
      subcategory: "expression",
      front: "passagem ida e volta",
      back: "往復チケット",
      example_pt: "Comprei uma passagem ida e volta para o Rio.",
      example_ja: "リオへの往復チケットを買った。",
      notes: "passagem = チケット、ida = 行き、volta = 帰り",
    },
    {
      id: "2026-04-01-vocab-010",
      category: "vocabulary",
      subcategory: "expression",
      front: "ônibus leito",
      back: "寝台バス",
      example_pt: "O ônibus leito é confortável e econômico.",
      example_ja: "寝台バスは快適で経済的だ。",
      notes: "leito = ベッド",
    },
    {
      id: "2026-04-01-vocab-011",
      category: "vocabulary",
      subcategory: "word",
      front: "com antecedência",
      back: "前もって、事前に",
      example_pt: "Compre com antecedência para economizar.",
      example_ja: "節約するために事前に買おう。",
      notes: "antecedência = 事前。com antecedência = in advance",
    },
    {
      id: "2026-04-01-vocab-012",
      category: "vocabulary",
      subcategory: "expression",
      front: "dividir as férias",
      back: "休暇を分割する",
      example_pt: "Dividir as férias permite viajar mais vezes.",
      example_ja: "休暇を分割することでより多く旅行できる。",
      notes: "",
    },
    {
      id: "2026-04-01-vocab-013",
      category: "vocabulary",
      subcategory: "word",
      front: "aproveitar",
      back: "楽しむ、活用する、最大限に生かす（to enjoy / to make the most of）",
      example_pt: "Dá para aproveitar mais a viagem na baixa temporada.",
      example_ja: "オフシーズンは旅行をより楽しめる。",
      notes: "aproveitar a viagem = 旅行を楽しむ／aproveitar o tempo = 時間を有効活用する",
    },

    // ---- フレーズ -------------------------------------------------

    {
      id: "2026-04-01-phrase-001",
      category: "phrase",
      subcategory: "travel",
      front: "Os preços dos hotéis caem pela metade.",
      back: "ホテルの値段が半額になる。",
      example_pt: "",
      example_ja: "",
      notes: "baixa temporada（オフシーズン）の文脈で使う",
    },
    {
      id: "2026-04-01-phrase-002",
      category: "phrase",
      subcategory: "travel",
      front: "Dá para aproveitar mais a viagem.",
      back: "旅行をより楽しめる。",
      example_pt: "",
      example_ja: "",
      notes: "dá para = ～できる（= é possível）",
    },
    {
      id: "2026-04-01-phrase-002b",
      category: "phrase",
      subcategory: "grammar",
      front: "dar para + 動詞の原形 の使い方は？",
      back: "「～できる / ～することが可能」\n= é possível / can\n\n構造: dá para ＋ 動詞原形",
      example_pt: "Dá para economizar muito na baixa temporada.\nNão dá para ir hoje.\nDá para vir amanhã?",
      example_ja: "オフシーズンにはたくさん節約できる。\n今日は行けない。\n明日来られますか？",
      notes: "口語でよく使う。主語なしで使えるのがポイント（= It is possible to...）。否定は「não dá para ～」",
    },
    {
      id: "2026-04-01-phrase-003",
      category: "phrase",
      subcategory: "travel",
      front: "Os preços podem subir até 40%.",
      back: "値段が最大40%上がることがある。",
      example_pt: "",
      example_ja: "",
      notes: "finais de semana（週末）/ feriados（祝日）の文脈",
    },
    {
      id: "2026-04-01-phrase-004",
      category: "phrase",
      subcategory: "travel",
      front: "Viajar bem não significa gastar muito.",
      back: "良い旅行 ≠ たくさん使うこと。",
      example_pt: "",
      example_ja: "",
      notes: "このレッスンの中心メッセージ",
    },
    {
      id: "2026-04-01-phrase-005",
      category: "phrase",
      subcategory: "travel",
      front: "Comprar com antecedência ajuda a economizar.",
      back: "前もって買うと節約になる。",
      example_pt: "",
      example_ja: "",
      notes: "passagem aérea（航空券）購入のコツ",
    },
    {
      id: "2026-04-01-phrase-006",
      category: "phrase",
      subcategory: "travel",
      front: "Valores mudam constantemente.",
      back: "値段は常に変わる。",
      example_pt: "",
      example_ja: "",
      notes: "航空券の価格変動を説明するときに使う",
    },

    // ---- 接続詞・意見表現 -----------------------------------------

    {
      id: "2026-04-01-connector-001",
      category: "connector",
      subcategory: "opinion",
      front: "Na minha opinião…",
      back: "私の意見では…",
      example_pt: "Na minha opinião, viajar mais vezes é melhor.",
      example_ja: "私の意見では、より多く旅行する方が良い。",
      notes: "意見を述べるときの定番表現",
    },
    {
      id: "2026-04-01-connector-002",
      category: "connector",
      subcategory: "opinion",
      front: "Do meu ponto de vista…",
      back: "私の観点から見ると…",
      example_pt: "Do meu ponto de vista, experiências são mais importantes do que luxo.",
      example_ja: "私の観点からすると、経験は贅沢より重要だ。",
      notes: "やや改まった表現",
    },
    {
      id: "2026-04-01-connector-003",
      category: "connector",
      subcategory: "opinion",
      front: "Eu acredito que…",
      back: "〜だと信じている、〜と思う",
      example_pt: "Eu acredito que planejar é essencial para economizar.",
      example_ja: "節約するには計画が不可欠だと思う。",
      notes: "acreditar = 信じる。やや強い確信",
    },
    {
      id: "2026-04-01-connector-004",
      category: "connector",
      subcategory: "opinion",
      front: "Eu acho que…",
      back: "〜と思う",
      example_pt: "Eu acho que viajar na baixa temporada é melhor.",
      example_ja: "オフシーズンに旅行する方が良いと思う。",
      notes: "日常でよく使う。acreditar より軽い",
    },
    {
      id: "2026-04-01-connector-005",
      category: "connector",
      subcategory: "contrast",
      front: "Por outro lado…",
      back: "一方で…",
      example_pt: "Viajar de carro é útil. Por outro lado, viajar de ônibus é confortável.",
      example_ja: "車での旅行は便利だ。一方、バスでの旅行は快適だ。",
      notes: "対比を示す。on the other hand",
    },
    {
      id: "2026-04-01-connector-006",
      category: "connector",
      subcategory: "addition",
      front: "Além disso…",
      back: "さらに、その上…",
      example_pt: "Além disso, viajar de ônibus é bem barato.",
      example_ja: "さらに、バスで旅行するのはとても安い。",
      notes: "追加情報を加えるとき。furthermore / moreover",
    },

    // ---- 言い換え（REFORMULAR）------------------------------------

    {
      id: "2026-04-01-reformular-001",
      category: "reformular",
      subcategory: "paraphrase",
      front: "Viajar na baixa temporada é mais barato.",
      back: "Viajar fora dos períodos movimentados custa menos.",
      example_pt: "Os preços diminuem quando há menos turistas.",
      example_ja: "観光客が少ない時期は値段が下がる。",
      notes: "模範解答。movimentados = 混んでいる",
    },

  ],
};
