window.LESSON_DATA_20260416 = {

  lesson: {
    id: "2026-04-16",
    date: "2026-04-16",
    title: "AULA 4: Processo Comunicativo e Vocabulário do Trabalho",
    theme: "コミュニケーション・仕事",
  },

  cards: [

    // ---- 単語・表現 ------------------------------------------------

    {
      id: "2026-04-16-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "aprofundar",
      back: "深める、深く掘り下げる（to deepen）",
      example_pt: "Nós vamos aprofundar mais no processo comunicativo.",
      example_ja: "コミュニケーションプロセスをもっと深く掘り下げましょう。",
      notes: "aprofundar = a（方向）+ profundo（深い）+ ar（動詞化）",
    },
    {
      id: "2026-04-16-vocab-002",
      category: "vocabulary",
      subcategory: "expression",
      front: "processo comunicativo",
      back: "コミュニケーションプロセス",
      example_pt: "O processo comunicativo é muito importante para o aprendizado.",
      example_ja: "コミュニケーションプロセスは学習においてとても重要だ。",
      notes: "",
    },
    {
      id: "2026-04-16-vocab-003",
      category: "vocabulary",
      subcategory: "expression",
      front: "medo de errar",
      back: "間違えることへの恐れ",
      example_pt: "O medo de errar publicamente bloqueia a comunicação.",
      example_ja: "人前で間違えることへの恐れがコミュニケーションを妨げる。",
      notes: "medo = 恐れ / errar = 間違える。medo de + 動詞原形",
    },
    {
      id: "2026-04-16-vocab-004",
      category: "vocabulary",
      subcategory: "word",
      front: "autocorreção",
      back: "自己修正（self-correction）",
      example_pt: "O excesso de autocorreção mental atrapalha a conversa.",
      example_ja: "過度な頭の中での自己修正が会話を妨げる。",
      notes: "auto（自己）+ correção（修正）",
    },
    {
      id: "2026-04-16-vocab-005",
      category: "vocabulary",
      subcategory: "expression",
      front: "tradução interna",
      back: "頭の中での翻訳（internal translation）",
      example_pt: "Evite a tradução interna JP → PT.",
      example_ja: "日本語→ポルトガル語の頭の中での翻訳を避けよう。",
      notes: "中級の壁。直接ポルトガル語で考えることが目標",
    },
    {
      id: "2026-04-16-vocab-006",
      category: "vocabulary",
      subcategory: "word",
      front: "improvisar",
      back: "即興する（to improvise）",
      example_pt: "É importante aprender a improvisar na conversa.",
      example_ja: "会話の中で即興する力をつけることが大切だ。",
      notes: "",
    },
    {
      id: "2026-04-16-vocab-007",
      category: "vocabulary",
      subcategory: "word",
      front: "reprogramar",
      back: "再プログラムする、習慣を作り直す（to reprogram）",
      example_pt: "O modelo de aula precisa reprogramar o comportamento comunicativo.",
      example_ja: "授業モデルはコミュニケーション行動を作り直す必要がある。",
      notes: "re（再び）+ programar（プログラムする）",
    },
    {
      id: "2026-04-16-vocab-008",
      category: "vocabulary",
      subcategory: "word",
      front: "comportamento",
      back: "行動、振る舞い（behavior）",
      example_pt: "Preciso mudar meu comportamento comunicativo.",
      example_ja: "自分のコミュニケーション行動を変えなければならない。",
      notes: "comportar（振る舞う）+ mento（名詞化）",
    },
    {
      id: "2026-04-16-vocab-009",
      category: "vocabulary",
      subcategory: "word",
      front: "proprietário",
      back: "オーナー、所有者（owner）",
      example_pt: "Um proprietário pode usar a casa de 10 a 30 dias por ano.",
      example_ja: "オーナーは年間10〜30日、家を使うことができる。",
      notes: "propriedade（所有物・不動産）の派生語",
    },
    {
      id: "2026-04-16-vocab-010",
      category: "vocabulary",
      subcategory: "word",
      front: "alugar",
      back: "貸す・借りる（to rent）",
      example_pt: "O proprietário aluga a casa para outros clientes.",
      example_ja: "オーナーが他のお客さんに家を貸す。",
      notes: "日本語と違い「貸す」「借りる」どちらの意味にもなる。文脈で判断",
    },
    {
      id: "2026-04-16-vocab-011",
      category: "vocabulary",
      subcategory: "word",
      front: "maioria",
      back: "大多数、ほとんど（majority）",
      example_pt: "A maioria dos proprietários cobra 100.000 yens por dia.",
      example_ja: "大多数のオーナーは1日10万円を請求する。",
      notes: "a maioria de ～ = ～の大多数",
    },
    {
      id: "2026-04-16-vocab-012",
      category: "vocabulary",
      subcategory: "expression",
      front: "engenheiro de inteligência artificial",
      back: "AIエンジニア",
      example_pt: "Eu trabalho como engenheiro de inteligência artificial.",
      example_ja: "私はAIエンジニアとして働いています。",
      notes: "inteligência artificial = 人工知能（AI）",
    },
    {
      id: "2026-04-16-vocab-013",
      category: "vocabulary",
      subcategory: "expression",
      front: "computação gráfica",
      back: "コンピュータグラフィックス（CG）",
      example_pt: "Computação gráfica é como uma maquete virtual.",
      example_ja: "コンピュータグラフィックスはバーチャルな模型のようなものだ。",
      notes: "",
    },
    {
      id: "2026-04-16-vocab-014",
      category: "vocabulary",
      subcategory: "expression",
      front: "maquete virtual",
      back: "バーチャルモデル、仮想模型（virtual mockup）",
      example_pt: "O sistema usa maquete virtual para visualizar o espaço.",
      example_ja: "そのシステムは空間を視覚化するためにバーチャルモデルを使う。",
      notes: "maquete = 建築模型。virtual = 仮想の",
    },

    // ---- フレーズ -------------------------------------------------

    {
      id: "2026-04-16-phrase-001",
      category: "phrase",
      subcategory: "work",
      front: "Um proprietário pode usar a casa de 10 a 30 dias por ano.",
      back: "オーナーは年間10〜30日、家を使うことができる。",
      example_pt: "",
      example_ja: "",
      notes: "de X a Y = X から Y まで（範囲の表現）",
    },
    {
      id: "2026-04-16-phrase-002",
      category: "phrase",
      subcategory: "work",
      front: "O proprietário aluga a casa para outros clientes.",
      back: "オーナーが他のお客さんに家を貸す。",
      example_pt: "",
      example_ja: "",
      notes: "alugar para ～ = 〜に貸す",
    },
    {
      id: "2026-04-16-phrase-003",
      category: "phrase",
      subcategory: "work",
      front: "O proprietário pode dar 1 dia de presente para outras pessoas.",
      back: "オーナーは他の人に1日分をプレゼントとして渡すことができる。",
      example_pt: "",
      example_ja: "",
      notes: "dar de presente = プレゼントとして渡す",
    },
    {
      id: "2026-04-16-phrase-004",
      category: "phrase",
      subcategory: "communication",
      front: "Parar de \"produzir frases\" e começar a conversar pensando em ideias.",
      back: "「文を作る」のをやめて、アイデアで考えながら会話し始める。",
      example_pt: "",
      example_ja: "",
      notes: "parar de + 動詞原形（〜するのをやめる）/ começar a + 動詞原形（〜し始める）",
    },

    // ---- 文法パターン ---------------------------------------------

    {
      id: "2026-04-16-phrase-005",
      category: "phrase",
      subcategory: "grammar",
      front: "ficar preso の意味と使い方は？",
      back: "「詰まる、行き詰まる」\n\nficar + 形容詞/過去分詞 = ～な状態になる",
      example_pt: "Estudantes japoneses ficam presos por medo de errar.\nFiquei preso na conversa.\nFicou feliz com a notícia.",
      example_ja: "日本人学習者は間違いへの恐れで詰まってしまう。\n会話で詰まってしまった。\n（彼女は）その知らせに喜んだ。",
      notes: "ficar + 状態語 は英語の「become / get + 形容詞」に相当する超頻出パターン",
    },
    {
      id: "2026-04-16-phrase-006",
      category: "phrase",
      subcategory: "grammar",
      front: "demais の使い方は？",
      back: "「〜すぎる」（too much / too + 形容詞）\n\n形容詞・副詞の後ろに置く",
      example_pt: "Respostas curtas demais.\nCaro demais!\nTrabalhou demais hoje.",
      example_ja: "短すぎる返答。\n高すぎる！\n今日は働きすぎた。",
      notes: "muito（とても）より強い。語順は 形容詞 + demais",
    },
    {
      id: "2026-04-16-phrase-007",
      category: "phrase",
      subcategory: "grammar",
      front: "de X a Y の使い方は？",
      back: "「X から Y まで」（範囲・幅を表す）",
      example_pt: "Pode usar a casa de 10 a 30 dias.\nCusta de 100 a 500 reais.\nAberto de segunda a sexta.",
      example_ja: "家を10〜30日使える。\n100〜500レアルかかる。\n月曜から金曜まで開いている。",
      notes: "数字・曜日・時間など幅広く使える。英語の from X to Y",
    },

  ],
};
