window.LESSON_DATA_20260514 = {

  lesson: {
    id: "2026-05-14",
    date: "2026-05-14",
    title: "AULA 7: Suavização, Diminutivos e Conectores Vivos",
    theme: "言葉の和らげ方・縮小辞・接続詞",
  },

  cards: [

    // ---- 重要単語・概念 -------------------------------------------

    {
      id: "2026-05-14-vocab-001",
      category: "vocabulary",
      subcategory: "word",
      front: "suavização",
      back: "言葉を和らげること（= softening）",
      example_pt: "Suavização é transformar frases diretas em versões mais naturais.",
      example_ja: "Suavização とは直接的な言い方をより自然なバージョンに変えることだ。",
      notes: "suavizar = 和らげる。ブラジルの社会的コミュニケーションの核心スキル",
    },
    {
      id: "2026-05-14-vocab-002",
      category: "vocabulary",
      subcategory: "word",
      front: "diminutivo",
      back: "縮小辞（= diminutive）",
      example_pt: "No Brasil, o diminutivo raramente é sobre tamanho — é sobre afeto ou suavização.",
      example_ja: "ブラジルでは縮小辞はサイズの話ではなく、愛情や和らげのためにほぼ使われる。",
      notes: "語尾 -inho / -inha を付ける。cafezinho, probleminha, pouquinho など",
    },
    {
      id: "2026-05-14-vocab-003",
      category: "vocabulary",
      subcategory: "word",
      front: "eufemismo",
      back: "婉曲表現（= euphemism）",
      example_pt: "\"Ele faleceu\" é um eufemismo para \"ele morreu\".",
      example_ja: "「彼は亡くなった」は「彼は死んだ」の婉曲表現だ。",
      notes: "直接的すぎる言葉を柔らかく言い換える表現",
    },
    {
      id: "2026-05-14-vocab-004",
      category: "vocabulary",
      subcategory: "expression",
      front: "meio + 形容詞",
      back: "ちょっと〜、やや〜（= kind of / somewhat）",
      example_pt: "É meio complicado. / Estou me sentindo meio estranho.",
      example_ja: "ちょっと複雑だ。/ なんか変な感じがする。",
      notes: "直接的な形容詞を和らげる定番パターン。meio difícil = ちょっと難しい",
    },
    {
      id: "2026-05-14-vocab-005",
      category: "vocabulary",
      subcategory: "word",
      front: "gracinha",
      back: "かわいいもの・かわいらしさ（= cutie / how cute!）",
      example_pt: "Nossa, que gracinha! (para bebês ou animais pequenos)",
      example_ja: "うわー、なんてかわいいの！（赤ちゃんや小動物に使う）",
      notes: "graca = かわいさ・魅力。que gracinha! は感嘆表現として使う",
    },
    {
      id: "2026-05-14-vocab-006",
      category: "vocabulary",
      subcategory: "expression",
      front: "faleceu / passou dessa pra melhor",
      back: "亡くなった（morreu の婉曲表現）",
      example_pt: "Ele faleceu ontem. / Ela passou dessa pra melhor.",
      example_ja: "彼は昨日亡くなった。/ 彼女は旅立った。",
      notes: "morreu（死んだ）は直接的すぎる。会話では faleceu か passou dessa pra melhor が自然",
    },
    {
      id: "2026-05-14-vocab-007",
      category: "vocabulary",
      subcategory: "expression",
      front: "Meus sentimentos. / Meus pêsames.",
      back: "お悔やみ申し上げます。（= My condolences.）",
      example_pt: "— Meu pai faleceu. — Meus sentimentos. / Meus pêsames.",
      example_ja: "「父が亡くなりました。」「お悔やみ申し上げます。」",
      notes: "pêsames はよりフォーマル。sentimentos はカジュアルにも使える",
    },
    {
      id: "2026-05-14-vocab-008",
      category: "vocabulary",
      subcategory: "expression",
      front: "divisor de águas",
      back: "ゲームチェンジャー、転換点（= watershed / game changer）",
      example_pt: "Entender o diminutivo é um divisor de águas para estrangeiros.",
      example_ja: "縮小辞を理解することは外国人にとってゲームチェンジャーだ。",
      notes: "直訳は「水の分かれ目」→ 大きな転換点・決定的な違い",
    },
    {
      id: "2026-05-14-vocab-009",
      category: "vocabulary",
      subcategory: "expression",
      front: "puxado no sal",
      back: "塩気が強い、しょっぱい（= heavy on salt）",
      example_pt: "A comida ficou um pouquinho puxada no sal, não?",
      example_ja: "料理がちょっとしょっぱかったよね？",
      notes: "puxado = 引っ張られた → 「強め」のニュアンス。puxado no sal = 塩が強い",
    },

    // ---- 縮小辞の特別用法（diminutivos especiais）----------------

    {
      id: "2026-05-14-phrase-001",
      category: "phrase",
      subcategory: "diminutivo",
      front: "um probleminha の本当の意味は？",
      back: "表面上は「小さな問題」→ 実際は大問題かもしれない",
      example_pt: "Temos um probleminha aqui... (= pode ser um erro de 1 milhão de euros)",
      example_ja: "「ちょっと問題がありまして…」（= 実は100万ユーロのエラーかも）",
      notes: "ブラジルでは縮小辞で深刻さをすぐには見せない。相手を驚かせないための文化的配慮",
    },
    {
      id: "2026-05-14-phrase-002",
      category: "phrase",
      subcategory: "diminutivo",
      front: "um cafezinho の本当の意味は？",
      back: "「ちょっとコーヒーでも」→「デリケートな話があります、15分ください」",
      example_pt: "Vamos tomar um cafezinho pra gente conversar?",
      example_ja: "「ちょっとコーヒーでも飲みながら話しませんか？」（= 大事な話があります）",
      notes: "コーヒーの話ではない。cafezinho = 「ちょっとした会話」の婉曲表現",
    },
    {
      id: "2026-05-14-phrase-003",
      category: "phrase",
      subcategory: "diminutivo",
      front: "dá uma olhadinha の本当の意味は？",
      back: "「ちょっと見て」→「じっくり慎重に確認してください」",
      example_pt: "Dá uma olhadinha com calma, viu?",
      example_ja: "「ゆっくりちゃんと確認してね？」（= しっかり見てほしい）",
      notes: "olhar = 見る → olhadinha = ちょっと見て → 実は「丁寧に深く確認して」の意味",
    },

    // ---- 言い換え練習（直接 → ソーシャル版）----------------------

    {
      id: "2026-05-14-phrase-004",
      category: "reformular",
      subcategory: "suavização",
      front: "Não gostei.",
      back: "Não gostei muito.",
      example_pt: "",
      example_ja: "「好きじゃなかった」→「あまり好きじゃなかった」",
      notes: "muito を加えるだけで一気に柔らかくなる",
    },
    {
      id: "2026-05-14-phrase-005",
      category: "reformular",
      subcategory: "suavização",
      front: "É difícil.",
      back: "É meio complicado.",
      example_pt: "",
      example_ja: "「難しい」→「ちょっと複雑ですね」",
      notes: "meio = ちょっと、やや。difícil → complicado に変えるとさらに柔らかい",
    },
    {
      id: "2026-05-14-phrase-006",
      category: "reformular",
      subcategory: "suavização",
      front: "Não entendi.",
      back: "Acho que não entendi bem o que você quis dizer.",
      example_pt: "",
      example_ja: "「分からなかった」→「おっしゃった意味がうまく理解できなかったようです」",
      notes: "acho que（〜と思う）+ não entendi bem（よく分からなかった）で丁寧さが増す",
    },
    {
      id: "2026-05-14-phrase-007",
      category: "reformular",
      subcategory: "suavização",
      front: "Espere um pouco.",
      back: "Espere um pouquinho. / Péra um pouquinho!",
      example_pt: "",
      example_ja: "「ちょっと待って」→「ちょっとだけ待ってね！」",
      notes: "Péra = Espera の口語短縮形。pouquinho で親しみやすさが増す",
    },
    {
      id: "2026-05-14-phrase-008",
      category: "reformular",
      subcategory: "suavização",
      front: "É muito bonito!",
      back: "Nossa, que gracinha!",
      example_pt: "",
      example_ja: "「とてもかわいい！」→「うわー、なんてかわいいの！」",
      notes: "赤ちゃんや小動物に使う。単なる形容詞より感情が豊かに伝わる",
    },
    {
      id: "2026-05-14-phrase-009",
      category: "reformular",
      subcategory: "suavização",
      front: "Eu não aguento.",
      back: "Preciso de um tempo.",
      example_pt: "",
      example_ja: "「もう無理」→「少し時間が必要です」",
      notes: "não aguento = 耐えられない（直接的）→ preciso de um tempo = 時間が必要（婉曲）",
    },
    {
      id: "2026-05-14-phrase-010",
      category: "reformular",
      subcategory: "suavização",
      front: "Esta comida está salgada.",
      back: "A comida está ótima, mas ficou um pouquinho puxada no sal, não?",
      example_pt: "",
      example_ja: "「この料理しょっぱい」→「料理は最高だけど、ちょっと塩が強かったかな？」",
      notes: "ótima で褒めてから but で指摘。não? で同意を求めてさらに和らげる",
    },
    {
      id: "2026-05-14-phrase-011",
      category: "reformular",
      subcategory: "suavização",
      front: "Você está atrasado!",
      back: "Você chegou um pouquinho atrasado, né?",
      example_pt: "",
      example_ja: "「遅刻してる！」→「ちょっと遅かったね？」",
      notes: "pouquinho で責める強さを緩める。né? で相手に同意を求める形にすることで攻撃性が消える",
    },

    // ---- 接続詞（conectores vivos）-------------------------------

    {
      id: "2026-05-14-connector-001",
      category: "connector",
      subcategory: "consequence",
      front: "então",
      back: "だから、それで（= so / then）",
      example_pt: "O verão está chegando, então vai ficar muito quente.\nEstou ficando gordo, então preciso tomar cuidado.",
      example_ja: "夏が近づいている、だからとても暑くなる。\n太ってきた、だから食べ物に気をつけないと。",
      notes: "因果関係・結論をつなぐ。英語の so に相当。会話の流れを自然につなぐ",
    },
    {
      id: "2026-05-14-connector-002",
      category: "connector",
      subcategory: "sequence",
      front: "aí",
      back: "そしたら、それで、そこで（= and then / so then）",
      example_pt: "Eu estava andando na rua, aí de repente caiu um vaso na minha cabeça.\nEle ficou jogando bola na chuva, e aí ele ficou doente.",
      example_ja: "道を歩いていたら、そしたら突然頭に花瓶が落ちてきた。\n雨の中でボールを蹴っていた、そしたら病気になった。",
      notes: "口語的な então。出来事の連続・意外な展開をつなぐ。会話でとても頻繁に使われる",
    },
    {
      id: "2026-05-14-connector-003",
      category: "connector",
      subcategory: "sequence",
      front: "então と aí の違いは？",
      back: "então = 論理的な結果（だから）\naí = 出来事の流れ・意外な展開（そしたら）",
      example_pt: "Estava lendo enquanto andava, aí acabei caindo.\nEstou cansado, então vou dormir cedo.",
      example_ja: "歩きながら読んでいたら、そしたら転んでしまった。\n疲れた、だから早く寝る。",
      notes: "aí は話し言葉で特に頻出。narrative（物語）ではほぼ aí を使う",
    },

  ],
};
